Feature/user register
shimotaroo/Yanbaru-Qiita-App pull request #10
Opened 2021-03-20 14:20 UTC by yuta-kanashiro

ユーザー登録に関する機能、画面を作成しました。
画面の変遷を確認するため、仮のヘッダーを作成してあります。
ヘッダーに関しては上村さんの担当なので、上村さんにpullをお願いする際に、僕が作成したヘッダーは削除していただくようにお願いしたいと思います。

2021-03-20 15:34 UTC, ryota100 commented
お疲れ様です。

composer.jsonファイルと
composer.lockファイルが
コンフリクトを起こしており、動作確認ができません。

(状況補足)
kaiさんがlaravel_uiを導入。
かなしろさんがlaravelcollectiveを導入。
導入時に書き込まれる、composerファイルでかなりコンフリクトが起きています。

（修正内容）
docker内で、
composer installが正常に起動するよう、コンフリクト解消をお願いします。
※composer installコマンドで共同開発相手が導入したものを使えるようになるため、これが動かないと同じ環境で開発できない。

難航しそうであれば、別branchで作り直すのも一つかもしれません。

以上、宜しくお願いします。

2021-03-20 18:05 UTC, yuta-kanashiro commented
ユーザー登録画面はLaravelCollectiveを利用していて、ログイン画面は利用していなかったので、LaravelCollectiveを利用しない形に統一しました。
composer installも実行できることを確認済みです。

2021-03-21 02:51 UTC, ryota100 commented
お疲れ様です。

composer installも問題なくでき、他の挙動もOK！です。

headerだけ、laravelcollectiveの書き方が使ってあったので、その点だけ理解しておいてもらえればと思います。(仮作成だからかと思いますが。)

これがマージされた際には、周りにcomposer installをしていただくよう周知お願いします。

2021-03-21 04:05 UTC, shimotaroo requested changes
レビューしました！
あと少し！！
頑張りましょう😆

※全体的にしっかり書けていて素晴らしいと思います！！！

2021-03-21 04:05 UTC, shimotaroo commented on src/routes/web.php
> +
- ユーザー登録
- ログイン
- ログアウト

のルーティングはこの下に既にある
```
Auth::routes();
```

という便利なもので全て追加されていますのでこちらの追記は不要です！
なので削除しておきましょう！

Dockerコンテナ内で
```
php artisan route:list
```
を実行すると上記ルーティングが諸々出てきます＆ルーティングの名前も決まっているのでそちらを使うのが良いですね😁

一度コマンドを実行してみてどんな情報が表示されるのか見てみてください！

2021-03-21 06:15 UTC, yuta-kanashiro commented
パスワードの半角英数字のバリデーションの追加、ルーティングの記述の変更をしました。

2021-03-21 13:55 UTC, shimotaroo approved these changes
LGTMです！！
マージします！

半角英数字であれば正規表現を使わず`'alpha_num'`でもOKですよ！

こちらに使用可能なバリデーションがまとまっていますので見てみてください！
https://readouble.com/laravel/6.x/ja/validation.html#available-validation-rules

2021-03-21 14:11 UTC, ryota100 approved these changes

2021-03-21 14:13 UTC, merged