ポート番号修正・ユーザー新規登録（諸石）
shimotaroo/Yanbaru-Qiita-App pull request #101
Opened 2021-06-17 13:53 UTC by minami0601

ポート番号修正とユーザー新規登録追加しました。
レビューお願いします。

ポート番号修正はブランチを分けて作業するべきでした。次回から気をつけます。

## 【追加】
- `User.php`→`$fillable`にterm追加
- `RegisterController.php`にtermとバリデーション追加
- userテーブルのマイグレーションファイルにtermカラムを追加
   →`php artisan migrate`実行
- `resources/lang`の中に`ja/validation.php`を追加

## 【変更】
- `config/app.php`のlocalをjaに変更
- `resources/auth/register.blade.php`のフロント変更
- `docker-compose.yaml`のポート番号・インデント変更

## 【削除】
なし

## 【仕様】
- バリデーションがエラーになった場合はリダイレクトする→ok
- バリデーションエラーになった場合は入力した値をフォームに保存する→ok
- バリエーションメッセージは各フォームの下に表示する→ok
- バリデーションメッセージは日本語で表示する→ok
- ユーザー登録処理後は記事一覧画面にリダイレクトする（ログイン状態なのでヘッダーがログイン後用になっている）→記事一覧画面は作成中なので、一旦`welcom.blade.php`に遷移。ヘッダーはログイン後用になっている。
- 画面遷移時に「名前」入力フォームにフォーカスされた状態にする→ok

2021-06-18 13:10 UTC, miki-mitsuki requested changes
確認しました。
全体的には素晴らしいと思います。

コードのコメントには記載していませんが`ユーザー登録処理後は記事一覧画面にリダイレクトする`が確認できませんでした。
コーディング規約の件と合わせてご確認いただければと思います。

2021-06-18 13:10 UTC, miki-mitsuki commented on src/app/User.php
> +        'name', 'email', 'password','term'
今回採用しているコーディング規約のPSR-2では`カンマの後には必ずスペースを入れる`となっていますので、修正していただきたいです。

2021-06-19 10:12 UTC, minami0601 commented
修正しました。
レビューお願いいたします。

- ユーザー登録処理後、記事一覧画面にリダイレクトさせる
- ユーザーマイグレーションファイルの`term`を`unsignedTinyInteger`に変更
- カンマの後にはスペースを追加

2021-06-19 15:18 UTC, miki-mitsuki approved these changes
確認しました。
修正点全て問題ありません。
この内容でマージします。

2021-06-19 15:18 UTC, merged