記事編集機能実装
shimotaroo/Yanbaru-Qiita-App pull request #105
Opened 2021-06-19 08:54 UTC by shingo-suzumura

【内容】
・`ArticleController`に`edit`,`update`メソッド追加。
・ルーティングを認証済ユーザーと未登録ユーザごとに指定。
・`ArticlePolicy`を作成し`AuthServiceProvider`にポリシーを追記し認可機能実装。
・`edit.blead.php`のバリデーションエラー時に編集した値を保持するよう仕様に変更。
・コード規約に基づき修正。

2021-06-19 11:18 UTC, mitsumasaanan commented on src/resources/views/articles/edit.blade.php
> +                    <form method="POST" action="{{ route('articles.update',['article'=>$article]) }}">
カンマ( , )の後にスペースつけましょう。

2021-06-19 14:49 UTC, shingo-suzumura commented
【変更点】
・1次レビューの修正。
・indexメソッドへのルーティングが重複していたので片方を削除しました。

2021-06-21 13:41 UTC, shimotaroo requested changes
レビューしました！
ポリシー、ルーティングの実装はバッチリです！
ちょっと難しいところもあるかもしれませんが、修正対応お願いします！

2021-06-21 13:41 UTC, shimotaroo commented on src/resources/views/articles/edit.blade.php
> +                    <form method="POST" action="{{ route('articles.update', ['article'=>$article]) }}">
コーディング規約を守れていない箇所があります！
探してみましょう！

2021-06-21 13:41 UTC, shimotaroo commented on src/resources/views/articles/edit.blade.php
> +                                    value="{{ $article->title == $article->title ? $article->title : old('title') }}"
```
$article->title == $article->title ? $article->title : old('title')
```

これは`$article->title == $article->title`は必ずtrueになると思いますが、どのようなロジックを考えていますでしょうか？

概要、URLも同様です。

2021-06-21 13:41 UTC, shimotaroo commented on src/resources/views/articles/edit.blade.php
> +                                    <input class="form-check-input" type="radio" name="category_id" id="category1" value="1" {{ $article->category_id == 1 ? 'checked' : '' }}/>
ラジオボタン4つともに共通ですが、これ、ラジオボタンの選択肢を変えた上でバリデーションに引っかかった場合、その選択後の情報は保持されますか？
確認してみてください！

2021-06-21 13:41 UTC, shimotaroo commented on src/resources/views/articles/index.blade.php
>  @section('content')
ここおかしい気がします。
ご確認ください！

2021-06-21 13:41 UTC, shimotaroo commented on src/resources/views/auth/verify.blade.php
> +@extends('layouts.view')
`src/resources/views/auth/verify.blade.php`はこの共同開発で使用しないので修正不要です。

2021-06-22 11:26 UTC, shingo-suzumura commented
【修正点】
・`action="{{ route('articles.update', ['article'=>$article]) }}"`をコード規約に基づき修正
・各フォームの値の保持をNull合体演算子に変更しました。
・ラジオボタンを値が保持されるように変更。
・`index.blade.php`は最新のdevelop-7-Aをマージして修正しました。
・`verify.blade.php`は使用しないため削除しました。

2021-06-23 09:05 UTC, shingo-suzumura commented
【修正点】
・スペースの抜けている箇所を再度修正。
【変更点】
・`index.blade.php`に編集画面に飛ぶボタンを実装。

2021-06-23 13:23 UTC, shimotaroo approved these changes
LGTMです！
お疲れ様でした！

2021-06-23 13:23 UTC, shimotaroo commented on src/resources/views/articles/edit.blade.php
>                          @method('PUT')
ここ不自然なインデントずれがあるのが気になりますが実装範囲外なのでスルーします！

2021-06-23 13:23 UTC, merged