記事投稿画面のフロント部分を作成(かずき)
shimotaroo/Yanbaru-Qiita-App pull request #109
Opened 2021-06-20 03:44 UTC by Kazuki1131

記事投稿画面のフロント部分を作成しました。
ご確認よろしくお願いいたします。

## 【仕様】
- カテゴリーのラジオボタンは「Laravel」「PHP」「Docker」「Web基礎」の4つとする　→OK
- 画面遷移時に「記事タイトル」入力フォームにフォーカスされた状態にする→OK

2021-06-20 23:44 UTC, miki-mitsuki requested changes
確認しました。
画面の作成は素晴らしいです。

viewのみを作成するなら考慮しておいた方が良い点と
docker-compose.ymlの件コメントしていますので、ご確認ください。

2021-06-20 23:44 UTC, miki-mitsuki commented on src/resources/views/articles/create.blade.php
> +                    <p class="form-text text-muted">50文字以内で入力してください。</p>
先にviewだけ作成される場合は、画面に表示されるコンテンツが多い状態（今回であればエラーメッセージも表示されている状態）が好ましいです。

2021-06-20 23:44 UTC, miki-mitsuki commented on docker-compose.yml
> +    image: mariadb:10.3
他の部分の変更は問題ないのですが、この部分の変更は他の方の作業に問題が出ると思うので元に戻していただければと思います。

2021-06-21 12:28 UTC, Kazuki1131 commented
ご指摘いただいた箇所を修正いたしました。
ご確認よろしくお願いいたします。

## 修正箇所
- バリデーションメッセージを追加
- docker-compose.ymlのイメージを元に戻す

2021-06-21 12:38 UTC, Kazuki1131 commented
ご指摘いただいた箇所を修正いたしました。
ご確認よろしくお願いいたします。

修正箇所
バリデーションメッセージを追加
docker-compose.ymlのイメージを元に戻す

2021-06-21 12:38 UTC, Kazuki1131 commented
ご指摘いただいた箇所を修正いたしました。
ご確認よろしくお願いいたします。

## 修正箇所
バリデーションメッセージを追加
docker-compose.ymlのイメージを元に戻す

2021-06-21 16:46 UTC, miki-mitsuki requested changes
確認しました。
docker-compose.ymlは無くなってしまうと、新たに共同開発に参加する人が出てきた場合、環境構築ができなくなるのでdocker-compose.ymlがあるような状態まで戻していただきたいです。

また、レイアウトの件もコメントしていますので合わせてご確認いただければと思います。

2021-06-21 16:46 UTC, miki-mitsuki commented on docker-compose.yml
> -version: '3.8'
このままだと、docker-compose.ymlが削除されてしまうことになるため、削除ではなく、変更がなかったことにしていただきたいです。

2021-06-21 16:46 UTC, miki-mitsuki commented on src/resources/views/articles/create.blade.php
> +                    <p class="form-text text-muted">50文字以内で入力してください。</p>
50字以上の文字を入力された場合、エラーが出るはずなので、ここもエラーメッセージが表示された状態で作成した方が良いです

2021-06-21 16:46 UTC, miki-mitsuki commented on src/resources/views/articles/create.blade.php
> +                    <p class="text-danger">有効なURLを指定してください。</p>
この2つのエラーは同時に出ることはないはずなので、片方で問題ないです

2021-06-22 00:20 UTC, Kazuki1131 commented on docker-compose.yml
> -version: '3.8'
docker-compose.ymlですが、ローカルで削除はしてなく、下記コマンドを実行してpushしたのですが、これだとリモートのファイルが削除されてしまうことになるのでしょうか？

`git rm --cached <FILE_NAME>`

その場合、docker-compose.ymlの追跡を除外できてかつリモートのファイルに影響を与えないようにすることは、どのようにすれば可能でしょうか？

2021-06-22 00:27 UTC, Kazuki1131 commented on src/resources/views/articles/create.blade.php
> +                    <p class="form-text text-muted">50文字以内で入力してください。</p>
こちらはmaxlenghを指定しているため意図的にバリデーションメッセージはつけなかったのですが、何か特別な方法でmaxlengthで指定した文字数を超える入力ができてしまう場合があるのでしょうか？

2021-06-22 00:27 UTC, Kazuki1131 commented on src/resources/views/articles/create.blade.php
> +                    <p class="text-danger">有効なURLを指定してください。</p>
承知しました！

2021-06-22 11:27 UTC, miki-mitsuki commented on docker-compose.yml
> -version: '3.8'
`.gitignore`や`git rm --cached`の内容を改めて確認したところ、docker-compose.ymlが削除されるのが正解でした。
思い違いをしていて申し訳ないです。
このままで問題ありません。

2021-06-22 11:35 UTC, miki-mitsuki commented on src/resources/views/articles/create.blade.php
> +                    <p class="form-text text-muted">50文字以内で入力してください。</p>
ブラウザのバージョンが古い場合（ただしかなり古いもの）や検証ツールを使った場合などで文字数以上の文字を入力できます。
そのため、バリデーションメッセージはつけた方が良いです。

2021-06-22 14:12 UTC, miki-mitsuki requested changes
docker-compose.ymlの件、勘違いしていて申し訳ないです。
エラーメッセージの件に関しては修正していただければと思います。

2021-06-23 02:34 UTC, Kazuki1131 commented
ご指摘いただいた箇所を修正いたしました。
ご確認よろしくお願いいたします。
## 修正箇所
- 記事タイトルにバリデーションメッセージを追加
- 記事URLの不要なバリデーションメッセージを削除

2021-06-23 18:14 UTC, miki-mitsuki approved these changes
確認しました。
修正箇所問題ありませんでしたので、マージします。

2021-06-24 17:09 UTC, Kazuki1131 commented
再度docker-compose.ymlを追跡対象に追加してみました。
ご確認よろしくお願いいたします。

2021-07-03 15:19 UTC, closed without merging