記事一覧画面作成完了
shimotaroo/Yanbaru-Qiita-App pull request #11
Opened 2021-03-25 04:32 UTC by yuta-kanashiro

・記事一覧画面を作成
・ログアウト機能の追加

完了しました。レビューをお願いいたします。

2021-03-25 14:35 UTC, ryota100 approved these changes
お疲れ様です。

記事の確認やログアウトなど、問題なしです！
全体通して、非常によくできてます😊

小さな点をいくつかコメントしましたので、ご確認ください。
宜しくお願いします。

2021-03-25 14:35 UTC, ryota100 commented on src/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::orderBy('created_at','desc')->paginate(5);
何をやっているのかコメントを書いていくといいです。
・理解が深まる。
・後で振り返りやすい
・共同開発者への情報共有
習慣つくととても力になると思います。

以下、画像による一例です。

![スクリーンショット 2021-03-25 23 30 55](https://user-images.githubusercontent.com/64177062/112489820-28a4e880-8dc2-11eb-8e13-2ee8dd5c63aa.png)

2021-03-25 14:35 UTC, ryota100 commented on src/database/seeds/ArticlesTableSeeder.php
> +            'updated_at' => '2021-03-07 07:25:42',
情報追加して、複数のでデータで確認しているのとてもいいですね✨

2021-03-25 14:35 UTC, ryota100 commented on src/resources/views/articles/articles.blade.php
> +
不要な行間は削除しましょう。

2021-03-25 14:35 UTC, ryota100 commented on src/resources/views/articles/articles.blade.php
> +
不要な行間は削除しましょう。

2021-03-25 14:35 UTC, ryota100 commented on src/resources/views/articles/articles.blade.php
> +
不要な行間は削除しましょう。

2021-03-25 15:17 UTC, ryota100 commented
OKです！

後、以後branch名は、極力周りと合わせるようにしてください。
(新しいbranch名の書き方をされていたので)

名前が書かれていたり、書かれてなかったり、真ん中に名前が書いてあったり、最後に書いてあったりしているので。
今後パターンが増えないように意識しておいもらえればと思います。

2021-03-26 12:50 UTC, yuta-kanashiro commented
articles.blade.phpファイルに@section('title', '記事一覧')を追加しました。

2021-03-26 15:33 UTC, shimotaroo requested changes
レビューしました！！

ページネーションもバッチリですし、全体的によくできていると思います！

いつくかコメント入れています！
（現場でも大切なことを細かいですが書いてます）

2021-03-26 15:33 UTC, shimotaroo commented on src/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::orderBy('created_at','desc')->paginate(5);
素敵なレビュー！！！！

2021-03-26 15:33 UTC, shimotaroo commented on src/app/Http/Controllers/ArticlesController.php
> +        ]);
ここ、修正不要ですがこう書くこともできます！（スッキリします）

```
return view('articles.articles', compact('articles'));
```

詳細はググってみてください！

あと`'articles.articles'`（articlesディレクトリのarticles.blade.php)は命名的にあんまりよくないですね...ww

僕なら
`articles.blade.php`ではなく、

- top.blade.php
- index.blade.php

とかにします！

せっかくなのでファイル名修正してみましょう！

2021-03-26 15:33 UTC, shimotaroo commented on src/resources/views/layouts/app.blade.php
>          @endif
これ、画面定義書に入ってないので削除しておきましょう！！

2021-03-26 15:33 UTC, shimotaroo commented on src/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::orderBy('created_at','desc')->paginate(5);
ここは

```
$articles = Article::orderBy('created_at','desc')->with(['user])->paginate(5);
```

と書くことをオススメします！

`->with()`を使うことでN+1問題を防ぐことができます！

参考記事（これらの記事を読んだ後必ず公式ドキュメントも読んでみてくださいね）
- https://qiita.com/wim/items/66ae4e3a58427f86cb5f
- https://qiita.com/tmf16/items/b9dd262c7738472c86d9
- 公式ドキュメント：https://readouble.com/laravel/5.8/ja/eloquent-relationships.html#eager-loading

2021-03-26 16:54 UTC, yuta-kanashiro commented
修正完了しました！
compact()、N+1問題については知らなかったので調べました。

・compact()....配列を短く書くことができる関数。
・N+1問題....DBから値の取得を行う際にSQLのクエリビルダを発行して情報を集めていく必要があるが、その際、余分にたくさんのクエリビルダを発行してしまい、少なからず表示速度等に悪影響を出してしまうこと。
・クエリビルダと....データベースからレコードを取得する際に SQL 文を組み立てて問い合わせを行いますが、それを簡単に組み立てる事の出来る機能。

2021-03-26 23:20 UTC, shimotaroo approved these changes
バッチリです！！！
LGTM😆

2021-03-26 23:20 UTC, shimotaroo commented on src/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::orderBy('created_at','desc')->with(['user'])->paginate(5);
Good！！

追加で説明しておくと、
withの引数には各モデルに定義したリレーション関数（今回だと↓）を入れます。
今回はArticleモデルからデータを取得する時にユーザー情報もViewで表示したいので`user()`を適用しているので合わせて取得したいデータによってここは増減します！

```
public function user()
    {
        return $this->belongsTo(User::class);
    }
```

2021-03-26 23:20 UTC, merged