マイグレーションファイル・シーダーファイル作成(諸石)
shimotaroo/Yanbaru-Qiita-App pull request #120
Opened 2021-06-24 01:24 UTC by minami0601

マイグレーションファイル・シーダーファイルを作成しました。
レビューお願いします。

## 【追加】
- 記事マイグレーションファイル追加
- 記事シーダーファイル追加
- カテゴリーマイグレーションファイル追加
- カテゴリーシーダーファイル追加
- ユーザーシーダーファイル追加
- `DatabaseSeeder.php`に記事、カテゴリーのシーダーファイル実行記述追加

## 【変更】
`DatabaseSeeder.php`の`$this->call(UsersTableSeeder::class)`をコメントアウト

## 【削除】
なし

## 【特記事項】
なし

2021-06-24 22:57 UTC, miki-mitsuki requested changes
確認しました。
全体的によく書けて素晴らしいです。
1点ユーザーテーブルに関するシーザーファイルの修正をお願いしたいです。

2021-06-24 22:57 UTC, miki-mitsuki commented on src/database/seeds/UsersTableSeeder.php
> +            'password' => bcrypt('sample1'),
Laravelではマニュアルにハッシュ化する時は
`Hash:make()`
を使う様に記載されています。
https://readouble.com/laravel/7.x/ja/hashing.html

そのため、今後は
`'password' => Hash:make('sample1'),`
のように書くのが望ましいです。

2021-06-24 22:57 UTC, miki-mitsuki commented on src/database/seeds/ArticlesTableSeeder.php
> +<?php
マイグレーションファイルはテーブルの作成
シーダーファイルはDBのテーブルへデータを流し込こむ
という役割の違いがあるので、マイグレーションファイルとシーダーファイルはブランチ分けた方が良いです。
（今回はこのままで問題ありません）

2021-06-25 11:26 UTC, minami0601 commented
ユーザーシーダーファイルのパスワード部分修正しました。
レビューお願いします。

2021-06-25 13:15 UTC, miki-mitsuki approved these changes
確認しました。
修正問題ありません。
マージします。

2021-06-25 13:15 UTC, merged