ユーザー情報編集画面(再提出)
shimotaroo/Yanbaru-Qiita-App pull request #122
Opened 2021-06-24 14:15 UTC by Yuuichi-M

３タスク同時にプルリクエストを上げてしまいましたブランチを削除して、再度プルリクエストを上げました。
【実装点】
・views配下にuserフォルダ作成。
　userフォルダ配下にedit.blade.pepを作成、ユーザー情報編集画面実装。
・UserController.php作成
　ユーザー情報編集画面表示処理の実装
・web.phpに処理追加
　ユーザー情報編集画面表示のルーティング追記

2021-06-24 23:43 UTC, shimotaroo requested changes
レビューしました👍

2021-06-24 23:43 UTC, shimotaroo commented on src/app/Http/Controllers/UserController.php
> +        $user = Auth::user();
editの引数にUserモデルのオブジェクトである$userを渡しているのでここで再定義すると引数に渡す意味がないと思います。
関数の引数を使うか、関数内で定義するか、どちらかにしましょう！

ルーティング見ると動的なパラメーターをとっていない仕様なので後者にしたほうが良いですね。

意味がわからなかったら質問してくださいね！

2021-06-24 23:43 UTC, shimotaroo commented on src/app/User.php
> +    protected $table = 'users';
この一文は必要ですか？
`$table`を定義するケースはどういう時か調べてみてください。

2021-06-24 23:43 UTC, shimotaroo commented on src/resources/views/commons/header.blade.php
> +
ここはインデントはそのままの方が個人的には見やすかったですね！
なお修正不要です。

2021-06-24 23:43 UTC, shimotaroo commented on src/resources/views/user/edit.blade.php
> +@extends('layouts.view')
編集画面にはデフォルトで現在のユーザー情報を各フォームに表示させましょう。

2021-06-27 16:22 UTC, Yuuichi-M commented
【修正点】
・UserController.php修正
　$user = Auth::user();を削除
・web.php修正
　第一引数を'/user/{id}/edit'に修正
・User.php
　protected $table = 'users' 削除
・edit.blade.php
　Null合体演算子で現在のユーザー情報を各フォームに表示
　
【その他修正点】
・header.blade.php
　VSCodeの拡張機能(php intelephense)のコード自動整形による影響で、
　インデントが変わっておりましたので、機能無効にし修正。
・UserRequest.php
　rulesメソッド、'email'のmax:255をmax:25に修正。

2021-06-30 14:27 UTC, Yuuichi-M commented
【変更点】
・UserRequest.php
　メールアドレスのバリデーション(重複チェック)を追記

2021-06-30 15:24 UTC, shimotaroo approved these changes
LGTMです🎉
バッチリです！！

2021-07-02 02:57 UTC, merged