教材修正
shimotaroo/Yanbaru-Qiita-App pull request #123
Opened 2021-06-24 14:34 UTC by hirotera

間違えたファイルで作業してしまい失礼致しました｡
修正しましたので確認よろしくお願いいたします｡
![スクリーンショット 2021-06-23 23 34 02](https://user-images.githubusercontent.com/60830985/123281076-58d86080-d544-11eb-850e-a5558b5ba4d2.png)
![スクリーンショット 2021-06-23 23 21 37](https://user-images.githubusercontent.com/60830985/123281439-a785fa80-d544-11eb-80cc-fb14605eb433.png)

2021-06-24 23:54 UTC, shimotaroo requested changes
レビューしました！
記事編集画面も同様ですm(__)m

2021-06-24 23:54 UTC, shimotaroo commented on src/resources/views/articles/create.blade.php
> +                            <small id="url" class="form-text text-muted">30文字以内で入力してください。</small>
`id="url"`は教材のミスですね...（他のフォームも）
消しても問題なければ消しておいて欲しいです。

2021-06-24 23:54 UTC, shimotaroo commented on src/resources/views/articles/create.blade.php
> +                                </span> --}}
このファイルのコメントは見にくくなるので消しましょう。
`is-invalid`は付けなくてOKです。

2021-06-24 23:54 UTC, shimotaroo commented on src/resources/views/articles/create.blade.php
> +                            <textarea class="form-control" id="summary"rows="6">記事概要</textarea>
`id="summary"rows="6"`
スペース空けておいてください。

2021-06-25 14:02 UTC, hirotera commented on src/resources/views/articles/create.blade.php
> +                            <small id="url" class="form-text text-muted">30文字以内で入力してください。</small>
消しても大丈夫だったので削除しました｡

2021-06-25 14:11 UTC, hirotera commented on src/resources/views/articles/create.blade.php
> +                                </span> --}}
エラー発生時挙動削除しました｡

2021-06-25 14:11 UTC, hirotera commented on src/resources/views/articles/create.blade.php
> +                            <textarea class="form-control" id="summary"rows="6">記事概要</textarea>
スペース修正しました｡

2021-06-26 12:49 UTC, shimotaroo requested changes
再度修正お願いします...m(__)m

エラーメッセージのところは全ファイル、全箇所共通です。

2021-06-26 12:49 UTC, shimotaroo commented on src/resources/views/articles/create.blade.php
> +                            </span>
エラーメッセージの表示は不要です！
（ここは受講生にさせます）

2021-06-26 12:49 UTC, shimotaroo commented on docker-compose.yml
> +      - 80:80
環境ファイルの修正はPRから除いてください。

2021-06-26 15:10 UTC, shimotaroo approved these changes

2021-06-26 15:10 UTC, merged