マイページフロント作成
shimotaroo/Yanbaru-Qiita-App pull request #128
Opened 2021-06-25 23:24 UTC by haruki0016

userマイページのフロント部分作成しました。
レビューお願いします。

## 【追加】
- `web.php`に`Route::get('user', 'UserController@show');`追加
- `UserController.php` 作成
- `UserController.php`にshowアクションを追加
- `show.blade.php`作成
- `user.css`作成
## 【変更】
なし

## 【削除】
なし

## 【特記事項】
なし

2021-06-26 14:24 UTC, miki-mitsuki requested changes
確認しました。
インデントのずれなど、気になった点いくつかコメントしていますのでご確認いただければと思います。

2021-06-26 14:24 UTC, miki-mitsuki commented on src/resources/views/user/show.blade.php
> +</div>
この閉じタグは不要だと思います。
この閉じタグに対応したdivの開始タグがあるか確認してみてください

2021-06-26 14:24 UTC, miki-mitsuki commented on src/resources/views/user/show.blade.php
> +                    <a href="#" class="px-2 btn btn-secondary" style="display:inline; border-radius:20px;">編集</a>
ソース管理の観点から、基本的にはcssを書く場合はsrc/public/css/user.cssに記述した方が良いです。
（CSSがいろんなファイルに書いてあると、変更があった場合にどこを確認すれば良いかわかりにくくなります）

2021-06-26 14:24 UTC, miki-mitsuki commented on src/app/Http/Controllers/UserController.php
> +<?php
ファイル名ですがコントローラーの場合、単数形、複数形どちらでも構わないのですが、先に挙げてくださったArticleのコントローラーがArticlesController.phpと複数形だったのでそちらに合わせていただいた方が良いと思います。
どちらにするかは一度チーム内で相談してみてください。

2021-06-28 15:21 UTC, haruki0016 reviewed
指摘事項修正しました。レビューお願い致します。 13d5bb7082eacd0b29ebc73db80abbdf41e578cd
### 【追加】
- `show.blade.php`のクラス名containerの後ろに`user-show-box01` 追加
- `show.blade.php`のクラス名ml-autoの後ろに `btn-box01`追加
- user.cssに `.user-show-box01.btn-box01a{border-radius:20px;}`追加
***
### 【変更】
-  ファイル名を`UserController.php`から `UsersController.php`に変更(複数形)
- `UsersController.php`のクラス名を `UsersController`に変更
- `web.php `の `UserController`の記述文を `UsersController`に変更
- `user.css`のインデントのずれを修正
- `user.css`の `dt`と `dd`のwidth幅を修正
- `index.blade.php `の誤った改行部分を修正(補正機能を一度解除して修正)
***
### 【削除】
- `show.blade.php`のcss記述部分 `style="display:inline;border-radius:20px;`削除
***

2021-06-29 12:12 UTC, miki-mitsuki commented on src/public/css/user.css
> +}
test

2021-06-29 13:51 UTC, haruki0016 reviewed
### 【変更】
- `user.css`の空白部分を削除

2021-06-29 13:57 UTC, haruki0016 commented
GMT時に指摘された空白部分を修正しました。911778053f6fee4616097000ef28b9f62a31e573

> ### 【変更】
> * `user.css`の空白部分を削除

2021-06-29 14:01 UTC, haruki0016 commented
> GMT時に指摘された空白部分を修正しました。
> 
> > ### 【変更】
> > 
> > * `user.css`の空白部分を削除

2021-06-29 23:16 UTC, miki-mitsuki approved these changes
確認しました。
画面としては問題なかったので、マージしますが、機能実装に取り入れていただきたいことを追記していますので、確認お願いいたします。

2021-06-29 23:16 UTC, miki-mitsuki commented on src/resources/views/user/show.blade.php
> +                <dd><a href="https://qiita.com/shimotaroo/items/6a909797e0139517b1bd">https://qiita.com/shimotaroo/items/6a909797e0139517b1bd</a></dd>
外部リンクの時は別タブを開いた方が良いので、`target= "_blank" rel="noopener"`をつけた方が良いです。
（対応は機能実装の際で構いません）
`target= "_blank" rel="noopener"`の詳しい意味は一度調べてみてください。

2021-06-29 23:16 UTC, merged