ArticlesControllerにviewを呼び出すメソッド追加(かずき)
shimotaroo/Yanbaru-Qiita-App pull request #132
Opened 2021-06-28 14:00 UTC by Kazuki1131

## 追加
なし

## 変更
- ArticlesControllerにviewのarticlesディレクトリのcreate.blade.phpを呼び出すメソッド追加

## 削除
なし

2021-06-29 21:56 UTC, miki-mitsuki commented on src/app/Http/Controllers/ArticlesController.php
> +        $this->middleware('auth');
今後、ArticlesControllerで機能を実装するはずの記事詳細画面はログインしていないユーザーも見れる画面のはずなので、ArticlesControllerの共通処理でログインをチェックしない方が良いです。

2021-06-29 22:11 UTC, miki-mitsuki submitted a review, later dismissed
確認しました。
Controllerの作り方自体は良いと思います。
1点気になった点がありましたので確認お願いいたします。

2021-06-29 22:16 UTC, miki-mitsuki requested changes
確認しました。
Controllerの作り方自体は良いと思います。
1点気になった点がありましたので確認お願いいたします。

2021-06-30 14:14 UTC, Kazuki1131 commented
ご指摘いただいていた部分の修正をいたしました。
コミットメッセージ間違えてしまいまして、正しくは「ログインしてなくても記事詳細画面を表示できるように修正」でございます。
ご確認よろしくお願いいたします。

2021-06-30 22:17 UTC, miki-mitsuki approved these changes
確認しました。
見落としていた`public function create()`の部分も修正されていて素晴らしいです。
問題ないのでマージします。

2021-06-30 22:17 UTC, merged