web.phpのarticles/createのルーティングを更新(かずき)
shimotaroo/Yanbaru-Qiita-App pull request #133
Opened 2021-06-28 14:13 UTC by Kazuki1131

## 追加
なし

## 変更
web.phpのarticles/createのルーティング部分を更新

## 削除
なし

2021-06-29 22:22 UTC, miki-mitsuki requested changes
確認しました。
アクションの使い方で気になる点があったので、ご確認お願いいたします。

2021-06-29 22:22 UTC, miki-mitsuki commented on src/routes/web.php
> +Route::get('/articles/create', 'ArticlesController@index')->name('article');
新規作成画面なので、`index`ではなく`create`アクションの方が良いです。

2021-06-30 14:15 UTC, Kazuki1131 commented
ご指摘いただいていた部分を修正いたしました。
ご確認よろしくお願いいたします。

2021-06-30 22:14 UTC, miki-mitsuki requested changes
確認しました。
修正に関しては問題兄です。
申し訳ないですが、前回のチェックで見落としていた点があったので、確認していただければと思います。

2021-06-30 22:14 UTC, miki-mitsuki commented on src/routes/web.php
> +Route::get('/articles/create', 'ArticlesController@create')->name('article');
`->name('article')`の部分ですが
ArticlesControllerのcreateアクションであることから
`->name('articles.create')`のような名前にした方が良いです。
（nameがarticleのような名前だと今後名前が被ってしまうため）
前回のチェックで見落としていて申し訳ないのです。

2021-07-01 12:35 UTC, Kazuki1131 commented
nameの部分修正いたしました！
ご確認よろしくお願いいたします。

2021-07-01 19:43 UTC, miki-mitsuki approved these changes
確認しました。
修正問題ありません。
マージします。

2021-07-02 03:23 UTC, Kazuki1131 commented
コンフリクト解消しました。
ご確認よろしくお願いいたします。

2021-07-02 21:03 UTC, miki-mitsuki approved these changes
確認しました。
問題なくコンフリクト解消できています！

2021-07-02 21:03 UTC, merged