記事一覧画面作成(かずき)
shimotaroo/Yanbaru-Qiita-App pull request #139
Opened 2021-07-03 13:36 UTC by Kazuki1131

## 【追加】
- ArticlesController.phpにindexアクションを追加
## 【変更】
- web.phpのindexアクションへルーティングの変更
- index.blade.phpにユーザーが投稿した記事が表示されるように変更

## 【削除】

## 【特記事項】

## 【実装した仕様】
- 記事は投稿日時を降順で表示させる（新しいのが1番上）
- 1画面に表示する記事件数は5件としてページネーションを実装する

## 【未実装の仕様】
- ログイン中のユーザーが投稿した記事（＝自分の記事）の場合のみ、「編集」、「削除」ボタンが表示されるようにする
- 「URL」をクリックすると別ウィンドウでQiitaのページに遷移させる
- N+1問題対策をする

2021-07-03 15:28 UTC, Kazuki1131 commented
追記
みなみさんのPRのマージ後に発生したコンフリクトは解消いたしました。

2021-07-04 11:55 UTC, Kazuki1131 commented
以下の機能を実装しました。

- ログイン中のユーザーが投稿した記事（＝自分の記事）の場合のみ、「編集」、「削除」ボタンが表示されるようにする
- 「URL」をクリックすると別ウィンドウでQiitaのページに遷移させる

2021-07-04 16:58 UTC, miki-mitsuki requested changes
確認しました。
全体的なコードの書き方はよいと思います。
数点気になった点がありましたので、ご確認いただければと思います。

また、【未実装の仕様】に
・N+1問題対策をする
をあげてくださっていますがこちらいかがでしょうか？
解消できているとのことでしたら、その旨を記載していただければと思います。

2021-07-04 16:58 UTC, miki-mitsuki commented on src/resources/views/articles/index.blade.php
> +                        @if($user == $article->user)
Eloquentを比較するのではなく、userのidを比較するようなコードの方が好ましいです。

2021-07-04 16:58 UTC, miki-mitsuki commented on src/app/Http/Controllers/ArticlesController.php
> +    }
細かいですが、`}`の後ろに余分な半角スペースがついているので、ご確認いただければと思います。

2021-07-04 16:58 UTC, miki-mitsuki commented on src/app/Http/Controllers/ArticlesController.php
> +        //記事を5件ずつ降順で取得
コメント残していて良いですね！
もしコメント残すなら、コメントにどのカラムの降順かまで記載した方がよいです。

2021-07-04 16:58 UTC, miki-mitsuki commented on src/resources/views/articles/index.blade.php
> +                        <p class="d-inline font-weight-bold">{{$article->user->name}}</p>
{{ }}の前後には半角スペース入れた方がよいです。
例）{{ $article->user->name }}

2021-07-05 15:49 UTC, Kazuki1131 commented
ご指摘いただいた部分修正しました。
N＋1問題については、以下のようにクエリが3回でレコードを取得できているので問題ないように思えるのですが、どうでしょうか…？
 
![スクリーンショット 2021-07-06 0 47 54](https://user-images.githubusercontent.com/82161767/124496131-ff99e800-ddf3-11eb-9082-211cb6f15afc.png)

2021-07-05 22:36 UTC, miki-mitsuki requested changes
確認しました。
N+1問題を含め、概ね修正に問題はありません。
一点だけ、{{}}の前後に半角スペースをつける対応が不十分な部分が見受けられたので、細かい点で申し訳ないですが、修正していただければと思います。

2021-07-05 22:36 UTC, miki-mitsuki commented on src/resources/views/articles/index.blade.php
> -                            <dd class="col-8"><a href="{{$article->url}}" target="_blank" rel="noopener">{{$article->url}}</a></dd>
{}の前後に半角スペースを入れるに関してですが、`href="{{$article->url}}"`の部分にも、適用していただければと思います。

2021-07-06 14:46 UTC, miki-mitsuki approved these changes
確認しました。
修正問題ありません。
マージします。

2021-07-06 14:46 UTC, merged