記事編集機能追加(諸石)
shimotaroo/Yanbaru-Qiita-App pull request #140
Opened 2021-07-04 01:22 UTC by minami0601

詳細編集機能を作成しました。
レビューお願いします。

【追加】
- web.phpにeditアクションとupdateアクションへのルーティングを定義
- ArticleController.phpにeditアクションとupdateアクションを追加
- `Category.php`にカテゴリーを取得するアクションを追加
- views/articlesにedit.blade.phpを作成
- 記事のフォームリクエストを作成、バリデーションを追記
- 認可機能追加

【変更】
- 記事詳細画面の編集ボタンのリンクを変更

【削除】
なし

【特記事項】
なし

【仕様】
- 画面遷移時に「記事タイトル」入力フォームにフォーカスされた状態にする→ok
- カテゴリーのラジオボタンは「Laravel」「PHP」「Docker」「Web基礎」の4つとする→ok
- バリデーションはフォームリクエストに定義する→ok
- バリデーションがエラーになった場合は記事編集画面にリダイレクトする→ok
- バリデーションエラーになった場合は直前に入力した値をフォームに保持する→ok
- バリデーションメッセージは各フォームの下に表示する→ok
- バリデーションメッセージは日本語で表示する→ok
- 記事投稿成功後は記事一覧画面にリダイレクトする→ok
- 記事詳細画面の「編集ボタン」から編集画面に遷移できるようにする→ok
- 認可機能を実装し、ID（上記でいう5）のところに、自分が投稿した記事ではない数字を直接URL欄に入力した時に403エラーを返すようにしてください。→ok

記事一覧ができ次第リンク追加。

2021-07-04 17:47 UTC, miki-mitsuki requested changes
確認しました。
インデントなどコードが綺麗にかけていて素晴らしいです。
2点機能面で気になった点がありますので、ご確認いただけますでしょうか？

2021-07-04 17:47 UTC, miki-mitsuki commented on src/resources/views/articles/edit.blade.php
> +                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $article->title ?? old('title') }}" autocomplete="title" aut
記事タイトル、記事概要、記事URLで`バリデーションエラーになった場合は直前に入力した値をフォームに保持する`の仕様が確認できませんでした。
一度ご確認いただけますでしょうか？

2021-07-04 17:47 UTC, miki-mitsuki commented on src/app/Policies/ArticlePolicy.php
> +        return $user->id === $article->user_id;
この部分ですが、
`src/app/Http/Controllers/ArticlesController.php`の
`$this->authorize('update', $article);`と内容が重複していて、また、認証も仕様通りに効いていないようですので、ご確認いただけますでしょうか？

2021-07-05 11:07 UTC, minami0601 commented on src/app/Policies/ArticlePolicy.php
> +        return $user->id === $article->user_id;
自分の認識ではPolicy.phpのupdateに記述した`return $user->id === $article->user_id;`をコントローラーの
`$this->authorize('update', $article);`で呼び出している認識です。
試しに`ArticlePolicy.php`を削除して`$this->authorize('update', $article);`だけにしましたがエラーが起きてしまいました。

認証の仕様ですが自分のローカルでは確認できました。
<img width="1434" alt="スクリーンショット 2021-07-05 19 48 30" src="https://user-images.githubusercontent.com/65294836/124462172-67d4d380-ddcc-11eb-9adc-9ed7b554f7cd.png">
ご確認ほどよろしくお願いします。
こちらのサイトを参考にしました。
http://www.rail-c.com/

2021-07-05 11:07 UTC, minami0601 commented on src/resources/views/articles/edit.blade.php
> +                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $article->title ?? old('title') }}" autocomplete="title" aut
こちら修正しました。

2021-07-05 22:28 UTC, miki-mitsuki requested changes
確認しました。
認証機能の部分は私の認識が間違っていました。申し訳ないです。
また、一点前回見落としていた部分で申し訳ないのですが、レイアウトの部分で仕様と異なる部分が見受けられたので、ご修正いただけますでしょうか？

2021-07-05 22:28 UTC, miki-mitsuki commented on src/resources/views/articles/edit.blade.php
> +                                    <input class="form-check-input  mr-5" id="category_{{ $id }}" type="radio" name="category_id" value="{{ $id }}"  {{ old('category_id', $article->category_id) == $i
前回見落としていたようで申し訳ないのですが、ここのラジオボタンの位置は以下の理由から左側の方がよいと思います。
・新規登録画面とのレイアウトの差をなくす
・UIの観点（一般的には左側にラジオボタンがあるはずなので、逆だと違和感があり使いにくく感じる人が増える）
申し訳ないですが修正していただければと思います。

2021-07-05 22:28 UTC, miki-mitsuki commented on src/app/Policies/ArticlePolicy.php
> +        return $user->id === $article->user_id;
改めて確認したところ、参考サイトは確認できませんでしたが、私の確認の仕方や認識が間違っていたようです。
申し訳ないです。

記載していただいている方法、認識であっていますので、本機能に関してはこのままマージします。

2021-07-05 22:48 UTC, minami0601 commented
レイアウト修正しました。
レビューお願いします。

2021-07-06 22:21 UTC, miki-mitsuki approved these changes
確認しました。
コメントの通り一度マージしますが、余力があるようでしたら、是非修正にトライしていただければと思います。

2021-07-06 22:21 UTC, miki-mitsuki commented on src/resources/views/articles/edit.blade.php
> +                                <label class="form-check-label mr-5" for="category_{{ $id }}">{{ $category }}</label>
確認しました。
PCのような画面の幅が大きい場合は問題ありません。
ただ、画面の幅を小さくしたとき
・`Web基礎`がの文字列が２段になってしまう
・`Web基礎`が枠からはみ出してしまう
問題があるようです。
今回は
・画面幅が大きい場合の表示は問題ない
・ここから先は直し始めると慣れていないうちはとても時間がかかる場合がある
上記を考慮し、一度マージします。
もし時間に余裕があり、フロントエンドも極めたいと考ええいらっしゃるのであれば、もう一度修正にトライしていただければと思います。

2021-07-06 23:57 UTC, minami0601 commented
コンフリクトの修正しました。
レビューお願いします。

## 変更点
- レスポンシブ対応のためにbootstrapのクラスを付与
- 記事一覧も完成していたので、編集ボタンにリンク追加

2021-07-07 23:58 UTC, miki-mitsuki approved these changes
確認しました。
コンフリクト対応は問題ありません。
レイアウト対応はまだよくなる余地はあるように感じたので、もしフロントエンドに興味があれば、もっと深く調べていてもよいと思います。
現段階ではこのレイアウトで十分なのでマージします。

2021-07-07 23:58 UTC, miki-mitsuki commented on src/resources/views/articles/edit.blade.php
> +                            </div>
レイアウト調整されて以前より対応できている幅は増えていてよいと思います。
ただ、カテゴリが増えた場合など、カテゴリを追加するだけでなく、CSSの調整も必要な書き方なので、余力があれば、他の書き方も模索していただければと思います。
（「項目が多くなった時、2行にする」などの対応をしておくとよいです）

2021-07-07 23:58 UTC, merged