Feature/harui/mypage
shimotaroo/Yanbaru-Qiita-App pull request #141
Opened 2021-07-05 14:17 UTC by haruki0016

マイページ画面のフロント部分を実装しましたので確認よろしくお願いします。

### 【追加】

- `show.blade.php`に`target= "_blank" rel="noopener"`追加(前回プルリク時指摘あり)

- `@foreach ($articles as $article)`を自分の投稿下の記事の表示をさせるために追加

- `UsersControllor.php`にログインした各ユーザーのデータが取れるためのコードを追加

_____
### 【変更】

- 名前/ 期生/ タイトル/ メールアドレス/ 投稿日時 を変数に変更

_____
### 【削除】
- `show.blade.php`の記事表示を１つ削除
_____

### 【特記事項】
- なし
_____

2021-07-06 23:18 UTC, miki-mitsuki commented on src/resources/views/user/show.blade.php
>          <div class="card-body pt-2 pb-5">
ヘッダーからマイページに遷移できないので、遷移できるように対応していただきたいです

2021-07-06 23:20 UTC, miki-mitsuki commented on src/resources/views/user/show.blade.php
>                  <dt>名前</dt>
前回見落としていて申し訳ないのですが、画面幅が狭くなった（スマホなどでみた）場合、見出しが右側によってみにくくなっているようです。
もし、余力があれば調整に挑戦していただければと思います。

2021-07-07 11:57 UTC, miki-mitsuki commented on src/resources/views/user/show.blade.php
> +                <div><i class="fas fa-user-edit mr-3"></i>投稿日時 : {{ $article->created_at }}</div>
投稿日時という項目なので時間も入っていて良いと思いますが、画面設計書のように日付だけ表示するということもよくらることなので、実装方法がわからない場合はこの機会に調べて頂けるとよいと思います。

2021-07-07 13:36 UTC, miki-mitsuki commented on src/resources/views/user/show.blade.php
>                  <a class="px-4 btn btn-secondary" href="#">戻る</a>
既にメンバーが作成済の画面でリンクつけられそうなものがあれば、現時点でリンクつけていただければと思います。
（チーム内でリンクつける人が決まっていれば、このプルリクで修正なくても構いません）

2021-07-07 13:41 UTC, miki-mitsuki requested changes
インデントなどコードの書き方はしっかりかけていて素晴らしいです。
機能面やレイアウト面で何点かコメントしていますが、
記事一覧画面からマイページにアクセスできるようにすることのみが、
最低限の対応行なっていただきたい対応です。
他に関してはご自身の余力やチームメンバーとの役割分担を踏まえて対応していただければと思います。
ご確認のほど、よろしくお願いいたします。

2021-07-12 15:15 UTC, haruki0016 commented
マイページ画面の修正と追加実装をしましたので確認お願いします。

**【追加】**

- ヘッダーからマイページに遷移できるように修正(指摘事項)
- レスポンシブに対応できるように修正(指摘事項)
- マイページの各ボタンから遷移できるように修正(編集ボタン以外) (指摘事項)
____
**【変更】**
- 日時表示から日付表示に変更(指摘事項)
____
**【削除】**
なし
__
**【特記事項】**
なし
_____

2021-07-13 14:14 UTC, haruki0016 commented
`src/app/Http/Controllers/UsersController.php`の中に**ユーザー情報変更画面**に遷移するためのコードの記載があったため削除しました。

2021-07-13 22:05 UTC, miki-mitsuki requested changes
確認しました。

- ヘッダーからマイページに遷移できるようにheader.blade.phpを修正(指摘事項)
- レスポンシブに対応できるようにuser.cssを修正(指摘事項)

は問題ないのですが、他の点でいくつか気になった箇所がありますので、ご確認いただけますでしょうか？

2021-07-13 22:05 UTC, miki-mitsuki commented on src/resources/views/user/show.blade.php
> +                <a class="px-4 btn btn-secondary" href="javascript:history.back()">戻る</a>
`javascript:history.back()`は戻るボタンによくある仕様なのですが、
今回は、画面提議書に`記事一覧画面`へ遷移すると記載されていますので記事一覧画面へのリンクが貼っていただければと思います。
（ちなみに`history.back()`はブックマークなどでサイトにきたユーザーは「戻る」ボタンへYanbaru Qiita
外に戻ってしまうリスクがあるなどの問題があるため、扱いに注意が必要なコードになります）

2021-07-15 14:12 UTC, haruki0016 commented
指摘事項修正しました、確認よろしくお願いします。

【変更】
7810a55

- `UsersController.php`/`web.php`の"index"の記述部分を"show"に変更
- `show.blade.php`の誤った閉じタグを変更
- `show.blade.php`の戻るボタンの遷移を記事一覧画面に変更

【変更】
6e98920

-  `header.blade.php`の{{ route('user.show') }}の空白部分修正

2021-07-15 14:29 UTC, haruki0016 commented
【変更】
e229b60
- 余計な空白があったため削除しました。

2021-07-16 14:07 UTC, miki-mitsuki approved these changes
確認しました。
スペースのつけ忘れ等も自ら気づけていて素晴らしいです。
修正点に問題がなかったのでマージします。

2021-07-16 14:09 UTC, merged