記事投稿時のバリデーションの実装
shimotaroo/Yanbaru-Qiita-App pull request #145
Opened 2021-07-07 09:22 UTC by Kazuki1131

## 追加
- ArticlesControllerにstoreメソッドを追加
- フォームリクエストを作成し、バリデーションルールを定義
- ヘッダーの「投稿する」ボタンに記事投稿画面へのリンクを追加

## 修正
- バリデーションエラー時のみエラー文が表示されるように記事投稿画面を修正
- バリデーションエラーでリダイレクトされても入力した値が保持されるように修正

## 削除
なし

## 仕様
- カテゴリーのラジオボタンは「Laravel」「PHP」「Docker」「Web基礎」の4つとする→OK
- 画面遷移時に「記事タイトル」入力フォームにフォーカスされた状態にする→OK
- バリデーションはフォームリクエストに定義する→OK
- バリデーションがエラーになった場合は投稿画面にリダイレクトする→OK
- バリデーションエラーになった場合は直前に入力した値をフォームに保持する→OK
- バリデーションメッセージは各フォームの下に表示する→OK
- バリデーションメッセージは日本語で表示する→OK
- 記事投稿成功後は記事一覧画面にリダイレクトする→OK

## 特記事項
投稿内容のデータベースへの追加はまた後日実装いたします。

2021-07-07 15:41 UTC, Kazuki1131 commented
二つ目のコミットで以下の機能追加と修正をしました。

## 追加
- Article.phpに複数代入におけるホワイトリストを定義
- ArticlesController.phpにフォームリクエストの値のデータベースへの追加機能を実装

## 修正
- ArticleRequest.phpとcreate.blade.phpを、Eroquentモデルのメソッドを使ってデータベースへ追加するときの便宜上、フォームのname属性とテーブルのカラム名が同一になるよう修正

2021-07-08 11:47 UTC, miki-mitsuki requested changes
確認しました。
インデントなどコードはきれいにかけていると思います。
何点か実装の仕方で気になった点にコメント残していますので、ご確認のほどよろしくお願いいたします。

2021-07-08 11:47 UTC, miki-mitsuki commented on src/resources/views/articles/create.blade.php
> +                <a href="{{ route('top') }">
TOP
画面に遷移できなかったので、ご確認いただけますでしょうか？

2021-07-08 11:47 UTC, miki-mitsuki commented on src/resources/views/articles/create.blade.php
> +            <form action="/articles/create" method="POST">
このままでも問題ないのですが、可能であればlaravelのコードを用いてURLを生成してみてください。
（laravelのルーティングで記載しておけば、万が一URLが変わった場合でも、viewファイルの修正が不要になるため）

2021-07-08 11:47 UTC, miki-mitsuki commented on src/resources/views/articles/create.blade.php
> +                    @enderror
エラーとしては表示としては問題ないのですが、ユーザーの入力にあったエラーを出せる方がベターです。
（例：何も入力されていない場合は「文字を入力してください」、51文字以上の場合は「タイトルを50文字以内で入力してください」と表示する）
教材の中にlaravelのコードを使って、簡単に英語のエラーを出すという課題があったと思いますが、それを応用することで、例のようなユーザーにあったエラーメッセージを日本語で表示することができるので、調べてみてください。

2021-07-08 11:47 UTC, miki-mitsuki commented on src/app/Http/Requests/ArticleRequest.php
> +            'title' => 'required|string|max:49',
50文字の場合も登録可能にしていただきたいです。

2021-07-08 13:41 UTC, Kazuki1131 commented
## 修正箇所
- 「戻る」ボタンでトップページに遷移されない不備を修正
- formのアクション属性をルートメソッドで指定するように修正
- バリデーション属性をカスタマイズし、$message変数でエラーメッセージを出力するように修正
- タイトルの文字数制限を50文字以内で修正(未満と勘違いしてました！笑)

2021-07-08 23:14 UTC, miki-mitsuki requested changes
確認しました。
全体的に修正していただいた箇所に問題はありません。
1点修正していただきたい箇所がありますのでご確認いただけますでしょうか？

2021-07-08 23:14 UTC, miki-mitsuki commented on src/app/Http/Controllers/ArticlesController.php
> +use App\Http\Requests\ArticleRequest;
6行目と重複していますので削除していただきたいです。

2021-07-08 23:18 UTC, miki-mitsuki commented on src/app/Article.php
>      protected $fillable = ['user_id', 'title', 'category_id', 'summary','url'];
見落としていましたが、`'summary',`の後ろに半角スペース入れていただきたいです。

2021-07-09 13:49 UTC, miki-mitsuki approved these changes
確認しました。
修正いただいた点全て問題ありません。

2021-07-09 14:04 UTC, merged