記事削除機能追加(諸石)
shimotaroo/Yanbaru-Qiita-App pull request #146
Opened 2021-07-08 12:16 UTC by minami0601

記事削除機能を作成しました。
レビューお願いします。

## 【追加】
- `web.php`にdestroyアクションへのルーティングを定義
- `ArticleController.php`にdestroyアクションを追加
- `Article.php`にSoftDeletesを追加
- 認可機能追加
- 一覧画面と編集画面に削除のリンク追加
- common.jsを作成し、確認のアラートを表示

## 【変更】
なし

## 【削除】
なし

## 【特記事項】
なし

## 【仕様】
- 削除処理は記事一覧画面、記事詳細画面、マイページ画面から行えるようにする。（ボタンは各画面の担当者が設置）→ok
(マイページ出来次第リンク繋ぎます)
- 削除方法は論理削除とする（物理削除にしない）→ok
- 論理削除完了後は記事一覧画面にリダイレクトする→ok
- 削除前に画面の通り、「記事を削除してもよろしいですか？」という確認のアラートを表示させ、「OK」を押した時に記事を論理削除する→ok
- 「キャンセル」を押した場合は削除しない→ok
- 上記の確認アラートはJavaScriptで実装する→ok

2021-07-08 23:48 UTC, miki-mitsuki requested changes
確認しました。
追加課題の部分まで対応されていて素晴らしいです。
一箇所、半角スペースのの抜けがあったので修正いただきたいです。
また、追加課題が一部途中になっているようでしたので、ご確認いただければと思います。

2021-07-08 23:48 UTC, miki-mitsuki commented on src/app/Article.php
> +    protected $fillable = ['user_id', 'title', 'category_id', 'summary','url'];
細かい指摘かつ以前のレビューで見落としていて申し訳ないですが、`'summary',`の後ろにも半角スペース入れていただきたいです。

2021-07-08 23:48 UTC, miki-mitsuki commented on src/app/Http/Controllers/ArticlesController.php
> +        return redirect('/')->with('flash_message', '記事を削除しました');
確認させていただきたいのですが、追加課題の
`・記事一覧画面にリダイレクトした時に「記事を削除しました」のフラッシュメッセージを表示する（3秒間でフェードアウトさせる）`
まで着手されていますでしょうか？
もし着手されているようでしたら、リダイレクト時のフラッシュメッセージが表示されていませんでしたので、ご確認いただけますでしょうか？
もし、まだ実装されていないとのことでしたら、`->with('flash_message', '記事を削除しました')`の部分は不要です。

2021-07-09 00:29 UTC, minami0601 commented
修正しました。
レビューお願いします。

## 変更点
- コンフリクト修正
- Article.phpに半角スペース付与
- フラッシュメッセージは未実装なので削除しました。別のブランチで実装します。

2021-07-09 13:43 UTC, miki-mitsuki approved these changes
確認しました。
修正点全て問題ありません。

2021-07-09 13:43 UTC, merged