CSVダウンロード機能追加(諸石)
shimotaroo/Yanbaru-Qiita-App pull request #150
Opened 2021-07-10 08:45 UTC by minami0601

CSVダウンロード機能を追加しました。
レビューお願いします。

## 【追加】
- コントローラー、`CsvController.php`を追加
- モデル、`Csv.php`を追加
- `web.php`にcsvExportアクションへのルーティングを定義
- `Csv.php`にメソッド追加
- 記事一覧画面にダウンロードボタン追加

## 【変更】
なし

## 【削除】
なし

## 【特記事項】
なし

2021-07-10 14:14 UTC, miki-mitsuki requested changes
確認しました。
全体的にしっかりとコードがかけていて素晴らしいです。
2点気になった点がありますので、ご確認いただければと思います。

2021-07-10 14:14 UTC, miki-mitsuki commented on src/app/Http/Controllers/CsvController.php
> +        $response->headers->set('Content-Type', 'application/octet-stream');
`application/octet-stream`はEXEファイルなどの実行ファイルを指すものなので、ここはCSVを指すContent-Typeに変更していただいた方が良いです。

2021-07-10 14:14 UTC, miki-mitsuki commented on src/resources/views/articles/index.blade.php
> +    @if ($articles->count())
記事がない場合、ボタンが表示されない考慮がなされていて素晴らしいです！

2021-07-10 14:14 UTC, miki-mitsuki commented on src/app/Csv.php
> +            ->leftJoin('users AS u', 'articles.user_id','=','u.id')
細かい部分ですが、`,`の後ろは半角スペース入れていただきたいです。

2021-07-10 23:06 UTC, minami0601 commented
修正しました。
レビューお願いします。

## 変更点
- `Content-Type`を`text/csv`に変更
- `Csv.php`に半角スペース付与

2021-07-11 11:15 UTC, miki-mitsuki approved these changes
確認しました。
修正点問題ありませんでしたので、マージします。

2021-07-11 11:15 UTC, merged