フラッシュメッセージ追加(諸石)
shimotaroo/Yanbaru-Qiita-App pull request #151
Opened 2021-07-12 11:07 UTC by minami0601

フラッシュメッセージを追加しました。
レビューお願いします。

## 【追加】
- `ArticlesController.php`にフラッシュメッセージ追加
- `flash_messages.blade.php`を作成し、`app.blade.php`に追記
- `style.css`を作成し、アニメーション追記
- 会員登録でRegisterUsersトレイトで定義されているregisterメソッドをオーバーライドし、フラッシュメッセージ追加
- `LoginController.php`のログイン部分にフラッシュメッセージ追加
- `LoginController.php`でuseしているAuthenticatesUsersトレイトのlogoutメソッドをオーバーライドし追

## 【変更】
- header.bleade.php,app.blade.phpのレイアウト修正

## 【削除】
なし

## 【特記事項】
会員登録、ログイン、ログアウトにもフラッシュメッセージを付けました。

2021-07-12 19:55 UTC, miki-mitsuki requested changes
確認しました。
動作した内容によって背景色が変わっていたり、追加課題になっていない箇所にもフラッシュメッセージ追加されていて素晴らしいです。
概ね問題ないのですが、1箇所だけインデントのズレが気になりましたのでご確認いただければと思います。

2021-07-12 19:55 UTC, miki-mitsuki commented on src/app/Http/Controllers/Auth/LoginController.php
> +}
インデントがずれていますので、ご確認いただければと思います。

2021-07-12 22:24 UTC, minami0601 commented
インデント修正しました。
よろしくお願いします。

2021-07-13 21:31 UTC, miki-mitsuki approved these changes
インデントの修正確認しました。
他は問題ないのでマージします。

2021-07-13 21:31 UTC, merged