検索機能の実装(かずき)
shimotaroo/Yanbaru-Qiita-App pull request #152
Opened 2021-07-12 11:24 UTC by Kazuki1131

## 追加
- Viewに検索フォーム追加
- バリデーションのためSearchRequest.phpを作成
- Articleモデルに検索機能のロジックを追加
- 検索機能メソッドを呼び出すためにコントローラーにsearchアクションを追加
- ルーターにsearchアクションへのルーティング追加

## 変更
なし

## 削除
なし

## 特記事項
なし

2021-07-12 20:28 UTC, miki-mitsuki requested changes
確認しました。
全体的にはしっかりとコードがかけているように感じました。
軽微な点ですが、何点か気になった点にコメント残しましたので、ご確認いただければと思います。

2021-07-12 20:28 UTC, miki-mitsuki commented on src/app/Http/Requests/SearchRequest.php
> +            'term' => '期',
細かいですが、検索の見出しが「期生」なので統一した方が良いと感じました。

2021-07-12 20:28 UTC, miki-mitsuki commented on src/app/Http/Requests/SearchRequest.php
> +            'term.digits_between' => '期は1~20で選択してください。',
ここも検索機能の見出しと揃えた方が良いと思います。

2021-07-12 20:28 UTC, miki-mitsuki commented on src/app/Article.php
> +            'retention_params' => [
このままでも問題ありませんが、他の部分との統一性の観点から、この部分はキャメルケースにしていただいた方が良いように感じました。

2021-07-13 14:19 UTC, Kazuki1131 commented
ご指摘いただいた箇所を修正しました。
ご確認よろしくお願いいたします。
## 修正
- 「期」を「期生」に修正
- `retention_params`を`retentionParams`に修正

2021-07-14 15:22 UTC, miki-mitsuki approved these changes
確認しました。
修正箇所全て問題ありませんでしたので、マージします。

2021-07-14 15:22 UTC, merged