シーダーファイルの作成
shimotaroo/Yanbaru-Qiita-App pull request #158
Opened 2021-08-01 13:10 UTC by MizukaNagura

## 見出し

- リスト1
- リスト2

> 引用

```
git log
```

    git log

2021-08-01 13:39 UTC, shimotaroo requested changes
レビュー盛りだくさんですが、頑張って修正お願いします！！
ファイトです！！

2021-08-01 13:39 UTC, shimotaroo commented on src/.env.example
> +DB_PASSWORD=yanbaru_password
レビュー後の修正は不要ですが、`.env.example`自体本来修正不要です。

2021-08-01 13:39 UTC, shimotaroo commented on src/.env.example
> +
こういう意味のない空行はなるべく無くしていきましょう！

2021-08-01 13:39 UTC, shimotaroo commented on src/database/seeds/ArticlesTableSeeder.php
> +        );
インデントは正しくは以下。
慣れるまでは難しいと思いますが、がんばりましょう！

```
DB::table('articles')->insert([
    [
        'id'=>'1',
        'title' =>'大阪',
        'summary' =>'たこ焼き',
        'user_id'=>'1',
        'category_id'=>'1',
        'url'=>'https://www.youtube.com/watch?v=CxasK4veEu8',
    ], 
    [
        'id'=>'2',
        'title' =>'沖縄',
        'summary' =>'泡盛',
        'user_id'=>'2',
        'category_id'=>'2',
        'url'=>'https://about.google/?fg=1&utm_source=google-JP&utm_medium=referral&utm_campaign=hp-header',
    ]
]);
```

- シーダーファイルの中身は`=>`の前後は半角スペースを空けましょう。
- 今回`Articles`って記事という意味なのでもう少し記事っぽいタイトルや概要（summary）にしておいてほしいですw（架空の技術記事っぽい感じで）
- テストデータは3件以上登録しておきたいのでテストデータを増やしてください。

他のシーダーファイルも同様ですのでこのレビューを参考に修正してみてください。

2021-08-01 13:39 UTC, shimotaroo commented on src/database/seeds/DatabaseSeeder.php
> +<<<<<<< Updated upstream
削除しておいてください。
（本来は削除しても`php artisan db:seed`が実行できることを確認すべきですが、問題ないと思うので今回は確認不要でOKです）

2021-08-01 13:39 UTC, shimotaroo commented on src/database/seeds/DatabaseSeeder.php
> +>>>>>>> Stashed changes
ここ削除。

2021-08-01 13:39 UTC, shimotaroo commented on src/database/seeds/UsersTableSeeder.php
> +        'password' => bcrypt('password'),
Laravel6はパスワードのハッシュ関数は`Hash::make()`を使うことが推奨されていますので、こちらに修正してください！（以下記事を参考に）

公式ドキュメント日本語ver
https://readouble.com/laravel/6.x/ja/seeding.html?header=%25E3%2582%25B7%25E3%2583%25BC%25E3%2583%2580%25E3%2582%25AF%25E3%2583%25A9%25E3%2582%25B9%25E5%25AE%259A%25E7%25BE%25A9

2021-08-01 13:39 UTC, shimotaroo commented on src/database/seeds/UsersTableSeeder.php
> +        'password' => bcrypt('passwordpassword'),
パスワードはテストデータといえど被らないものにすべきなので修正しておきましょう！
`passwordpasswordpassword`とかでOKです。

※その下も併せて修正

2021-08-02 12:15 UTC, shimotaroo requested changes
レビューしました！
修正頑張りましょう！！

2021-08-02 12:15 UTC, shimotaroo commented on src/database/seeds/ArticlesTableSeeder.php
> +
1回目のPRでレビューしましたが、こういう空行は絶対入れないようにしましょう！

2021-08-02 12:15 UTC, shimotaroo commented on src/database/seeds/ArticlesTableSeeder.php
> +
ここもです。

2021-08-02 12:15 UTC, shimotaroo commented on src/database/seeds/ArticlesTableSeeder.php
> +        [
15〜46行目はインデント1個深くするのが正解です。
（僕の1回目のレビューしっかり見ましょう）

2021-08-02 12:15 UTC, shimotaroo commented on src/database/seeds/DatabaseSeeder.php
> +
空行。

2021-08-02 12:15 UTC, shimotaroo commented on src/database/seeds/UsersTableSeeder.php
> +]);
このファイルはインデントを見直しましょう！

2021-08-02 12:15 UTC, shimotaroo commented on src/.env.example
> +DB_PASSWORD=yanbaru_password
再度修正が必要なのでここの修正戻しておいてください。

2021-08-02 12:15 UTC, shimotaroo commented on src/.env.example
> +
再度修正が必要なのでここの空行はなくしておいてください。

2021-08-02 12:17 UTC, shimotaroo requested changes

2021-08-02 12:17 UTC, shimotaroo commented on src/database/seeds/CategoriesTableSeeder.php
> +    ]);
インデント見直しましょう！

2021-08-03 13:32 UTC, MizukaNagura reviewed
* 前々回のcommitで、おおよそのインデント修正をしました。
! https://github.com/shimotaroo/Yanbaru-Qiita-App/pull/158/commits/68223f4b862a9816ddfdd07fd8354f4582a48ffe

*  前回のcommitで.env.exampleの修正をしました。
! https://github.com/shimotaroo/Yanbaru-Qiita-App/pull/158/commits/3c488360b5ace540380360260d905b217d1c8087

* 最新のcommitで、インデントの微調整をしました。

インデントは要チェックで修正させていただきました。
恐れ入りますが、ご査収の程よろしくお願いいたします。

2021-08-03 14:47 UTC, shimotaroo approved these changes
LGTM

2021-08-03 14:47 UTC, merged