ログイン機能の作成
shimotaroo/Yanbaru-Qiita-App pull request #160
Opened 2021-08-08 14:45 UTC by MizukaNagura

## 実装したこと
* ログイン機能の表示
getメソッド使用して、ログイン画面の表示をしました。
また、@errorを使用して表示が異なる場合にエラー表示をするようにしました。

* ログイン機能の送信
POSTメソッドを使用して、ログイン内容の送信ができるようにしました。

ゆーたろーさんのお力によって解決できました。
特にトレイトの中身を復習をして先に進みたいです。

恐れ入りますが、ご査収の程よろしくお願いいたします。

2021-08-08 23:44 UTC, shimotaroo requested changes
1点だけ不要な空行削除が入ってしまっています...！
ここだけ修正しましょう！
（他の修正箇所はバッチリです🎉）

2021-08-08 23:44 UTC, shimotaroo commented on src/app/Http/Controllers/Auth/LoginController.php
>  class LoginController extends Controller
ここの空行は戻す

2021-08-09 10:37 UTC, MizukaNagura commented
LoginController.phpで、空行を元に戻しましたので、宜しくお願いいたします！

2021-08-09 13:57 UTC, shimotaroo approved these changes

2021-08-09 13:57 UTC, merged