ログアウト機能の作成
shimotaroo/Yanbaru-Qiita-App pull request #161
Opened 2021-08-10 13:20 UTC by MizukaNagura

## app.blade.phpでの、ログアウト機能の作成をしました。
* href="{{ route('logout') }}でログイン画面に飛ぶようにしました。
* onclick="event.preventDefault(); document.getElementById('logout-form').submit()で、クリックしたらid指定させているlogout-formに一致するform id="logout-form" action="{{ route('logout') }}" method="POST"をさせて、ユーザーがログアウトの状態になっているようにしました。

ログインからログアウトの一連をブラウザ上で確認済です。
お忙しいところ恐縮ですが、ご査収の程よろしくお願いいたします！

2021-08-10 22:27 UTC, shimotaroo requested changes

2021-08-10 22:27 UTC, shimotaroo commented on src/resources/views/layouts/app.blade.php
> +                                {{ csrf_field() }}
ここはユーザー登録画面、ログイン画面と同じ書き方をしましょう！
`{{ csrf_field() }}`が何を意味しているのかがわかれば何に書き換えれば良いのかが分かります。

※`{{ csrf_field() }}`でも動きますが、コードの統一性の面でのレビューです。

2021-08-11 13:14 UTC, shimotaroo requested changes

2021-08-11 13:14 UTC, shimotaroo commented on src/resources/views/layouts/app.blade.php
> +                            </form>
すみません、ここレビュー漏れてました
インデントが1つ入り過ぎていますので修正ください！

2021-08-11 13:45 UTC, MizukaNagura commented
たびたびすみません！
``app.blade.php<form>``のインデントを１つ消しましたので、
ご確認のほどよろしくお願いいたします！

2021-08-11 14:18 UTC, shimotaroo approved these changes

2021-08-11 14:18 UTC, merged