記事一覧画面の実装
shimotaroo/Yanbaru-Qiita-App pull request #162
Opened 2021-08-14 14:10 UTC by takayaseiwa

実装したこと
-------
・シーダーファイルに登録しているデータを繰り返しして表示
・ログインしているユーザーにだけ編集・削除ボタンを実装
・詳細を見るボタンを押すとshow.blade.phpに遷移するように実装

シーダーファイルに登録しているデータを繰り返しして表示
-------
・ArticleControllerにて```$articles = Articles::with('user')->orderBy('created_at','desc')->paginate(5);```を
    記述しArticlesテーブルの全レコードを取得しつつwithメソッドを使い、何回もDBにアクセスするのを防ぎ
　N+1問題を解決するようにした。
・index.blade.phpにてユーザー名や記事のタイトル名などは```@foreach ($articles as $article)```を使い
　繰り返しにて表示するように実装した。

ログインしているユーザーにだけ編集・削除ボタンを実装
-------
・```@if(Auth::id() == $article->user->id)```を使用することにより、ログインしたユーザーにだけ
　編集と削除のボタンが出てくるように実装した。
    　現段階では投稿機能がないためボタンは見えないですが、if文を抜かした場合で実装すると
　ちゃんと画面上にはボタンが表示されていました。

詳細を見るボタンを押すとshow.blade.phpに遷移するように実装
-------
・詳細を見るの遷移先としてshow.blade.phpに行くように実装しました。
    ルーティングにも```Route::resource('articles', 'ArticleController', ['only' => ['show']]);```を実装し
　一覧画面からボタンを押すと詳細画面に飛ぶようにしました。
　編集・削除ボタンのルーティングまでは設定していません。

2021-08-14 15:18 UTC, shimotaroo requested changes

2021-08-14 15:18 UTC, shimotaroo commented on src/app/Http/Controllers/ArticleController.php
> +        $articles = Articles::with('user')->orderBy('created_at','desc')->paginate(5);
withメソッド、素晴らしいです！

2021-08-14 15:18 UTC, shimotaroo commented on src/app/Http/Controllers/ArticleController.php
> +        return view('articles.show',['articles' => $article]);
```
return view('articles.show',['articles' => $article]);
```

以下のヒントを参考に2点、修正してみましょう。

- PSR-2でコンマの後には何が必要ですか？
- `['articles' => $article]`に違和感ありません？

2021-08-14 15:18 UTC, shimotaroo commented on src/app/User.php
> +    }
少し意地悪な質問です。
このリレーションメソッドは一覧画面においてどのような働きがあると思いますか？？

2021-08-15 03:45 UTC, takayaseiwa commented on src/app/Http/Controllers/ArticleController.php
> +        $articles = Articles::with('user')->orderBy('created_at','desc')->paginate(5);
ありがとうございます！

2021-08-15 03:46 UTC, takayaseiwa commented on src/app/Http/Controllers/ArticleController.php
> +        return view('articles.show',['articles' => $article]);
・PSR-2でコンマの後には何が必要ですか？
→こちらスペースを一つ入れました。

・['articles' => $article]に違和感ありません？
→['article' => $article]に修正しました。

2021-08-15 03:58 UTC, takayaseiwa commented on src/app/User.php
> +    }
hasManyはこの場合、一人の投稿者に対して複数の投稿があるということを表すメソッドになるかと思います。
現在は一人の投稿者につき一つの投稿しかないですが、今後一人の投稿者につき複数の投稿が存在するようになれば、それぞれのデータにアクセスするためのメソッドとしてhasManyが必要になってくるのでははないかと考えました。

2021-08-15 05:18 UTC, shimotaroo requested changes

2021-08-15 05:18 UTC, shimotaroo commented on src/app/Http/Controllers/ArticleController.php
> +    public function show(Articles $article)
完全に漏れていました...！！
モデルファイルは単数系.phpで定義するのがスタンダードなので`Article.php`に変更してください！
モデルの元ファイルも修正お願いします。

2021-08-15 05:18 UTC, shimotaroo commented on src/app/User.php
> +    }
回答としては完璧です！！
関係性のこともしっかり理解されていてすばらしいです！
現時点では「そのユーザーが投稿した記事内容」を取得する必要がないのでこのメソッド自体定義が不要ということですね。（あっても良いですがw）
定義していただいたので一旦はこのままにしておきましょう

2021-08-15 06:15 UTC, shimotaroo approved these changes

2021-08-15 06:15 UTC, merged