User、ArticleテーブルのマイグレーションファイルとSeeder作成
shimotaroo/Yanbaru-Qiita-App pull request #17
Opened 2021-04-08 12:50 UTC by yuqi1020

User、ArticleテーブルのマイグレーションファイルとSeederファイルの作成が完了したので、レビューお願いします！

2021-04-08 16:13 UTC, miki-mitsuki reviewed
インデントなど、コードはきれいにかけていると思います。
何点か気になった点にコメント残していますので、ご確認いただければと思います。

2021-04-08 16:13 UTC, miki-mitsuki commented on src/database/seeds/UserTableSeeder.php
> +<?php
`php artisan db:seed`でDBにSeederファイルのデータを流し込む際、`src/database/seeds/DatabaseSeeder.php`も編集する必要があると思いますのでご確認いただけますでしょうか。
また、Seederファイルからのデータの流し込みをまだ一度も行っていないようでしたら、提出前に一度試していただければと思います。

2021-04-09 08:54 UTC, yuqi1020 commented
ご指摘の箇所を修正しましたので、再レビューお願いいたします！

2021-04-09 22:38 UTC, miki-mitsuki reviewed
確認しました。
修正の方向性は問題ありません。
2点ほど気になった点がありますので、ご確認いただければと思います。

2021-04-09 22:38 UTC, miki-mitsuki commented on src/database/seeds/UsersTableSeeder.php
- テストデータの数に関して

別ブランチで作成されているcommentsテーブルのseederファイルを確認したところ、usersテーブル、articlesテーブルともにidが5まであることが想定された作りになっていました。
commentsテーブルは外部キーの設定がされており、このままではマージしてseederファイルを実行した際にエラーが出ることになると思います。
テストデータは多い方が都合がよい場合が多いので、usersテーブル、articlesテーブルのseederファイルを修正していただけますでしょうか。
（チーム内でテストデータに関しての話し合いができれば上記以外の方法でも問題ありません）

2021-04-10 03:24 UTC, yuqi1020 commented
修正しました。
再レビューお願いいたします！

2021-04-10 03:38 UTC, yuqi1020 commented
修正しました。
再レビューお願いいたします！

2021-04-10 15:19 UTC, miki-mitsuki reviewed
別ブランチでの誤字の対応をしていただきありがとうございます。
前回指摘させていただいた内容に関しては問題ないのですが、今回のしていただいた誤字の対応に関して1点修正していただきたい部分がありますのでご確認お願いいたします。

2021-04-10 15:19 UTC, miki-mitsuki commented on src/database/migrations/2021_04_08_163106_create_comments_table.php
> +        Schema::create('comments', function (Blueprint $table) {
対応ありがとうございます。
別ブランチでの確認時、誤表記があることに気付きませんでした。
申し訳ないです。

2021-04-10 15:19 UTC, miki-mitsuki commented on src/database/seeds/CommentsTableSeeder.php
> +            "comments" => "分かった。"
こちらも修正ありがとうございます。
commentsテーブルのコメントカラムですが、カラム名は単数系にするのが基本です。
（画面提議書でもcommentとなっています）
そのため、こちらは修正前に戻していただいてsrc/database/migrations/2021_04_08_163106_create_comments_table.php側を修正していただけますでしょうか？

2021-04-10 15:53 UTC, miki-mitsuki commented on src/database/seeds/CommentsTableSeeder.php
> +            "comments" => "分かった。"
https://github.com/shimotaroo/Yanbaru-Qiita-App/pull/17/commits/ec4acd3ed8e684acc0a548fba3c045dd0969af6c
で修正していただいているの確認しました。
確認漏れ失礼いたしました。

2021-04-10 16:06 UTC, miki-mitsuki approved these changes
commentsテーブルの修正確認しました。
問題ありません。

ブランチ・PRを分け方に関してですが、基本的に1つの機能に付き1つのブランチで対応すべきなので、今後はマイグレーションファイル用、シーダーファイル作成用でブランチ・PRを分けていただいた方が良いです。
（このタイミングでの指摘となってしまい申し訳ないです。今回はこのままで問題ないと思います。）

2021-04-11 06:04 UTC, shimotaroo requested changes
レビューしました！！

大きな問題はなくよくできていると思います👍👍👍

シーダーファイルのデータの内容だけ修正してみてください！！

2021-04-11 06:04 UTC, shimotaroo commented on src/database/seeds/ArticlesTableSeeder.php
> +        $users = App\User::find(1);
この書き方、内容的というか処理的には問題ないのですが、今回の例でいくと
`$user`はid=1のユーザーになるので、テストデータは全てid=1のユーザーが投稿した記事データになるはずです。

テストデータはいろいろなパターンのデータを準備するのが良いので、
```
'user_id' => 
```
を各データに持たせた方が実現しやすいと思います！！

2021-04-11 07:29 UTC, yuqi1020 commented
修正しました。
修正内容は、2回のコミットに分けています。
・1回目　Seederファイル（Comments、User）の値を連想配列化
・2回目　ハッシュ関数修正、SrticlesTableSeeder修正

複数回のコミットになってしまい、申し訳ございませんが、よろしくお願いします。

2021-04-11 11:45 UTC, shimotaroo approved these changes
LGTMです👍👍👍👍👍
マージします！！

2021-04-11 11:45 UTC, merged