Feature/kataoka/register user
shimotaroo/Yanbaru-Qiita-App pull request #178
Opened 2021-08-28 03:25 UTC by Kataoka-PHP

［変更目的］
ユーザー登録処理を実装し、ログインおよび、ログアウトが可能な状態とするため

［変更内容］
　＜CREATE＞
　　・resources/lang/ja/validation.php
　　└バリデーションメッセージの日本語化のため、日本語パッケージをインストール

　　・app/Http/Controllers/ArticlesController.php
　　└記事一覧ページを表示するため、コントローラーを作成

　＜UPDATE＞
　　・app/User.php
　　└ユーザー登録フォームの項目としてterm（期数）を追加

　　・app/Http/Controllers/Auth/RegisterController.php
　　└ログイン後に、記事一覧画面に飛ばすための処理を追記
　　└バリデーションの項目（term）を追記

　　・config/app.php
　　└言語仕様を英語から日本語に変更

　　・routes/web.php
　　└記事一覧画面のルーティングを追記
　　└ユーザー登録を行うためのルーティングを追記

　　・resources/views/auth/register.blade.php
　　└バリデーションに関する処理を追記

［確認結果］
・手動で動作確認を行い、バリデーション内容および、画面定義書の仕様を満たしていることを確認した。

※ログイン前後のヘッダー作成についてプルリクが未承認のため、記事一覧画面にリダイレクトした際、ヘッダーがログイン後のものになっていませんが、ジーコさんからユーザー登録処理のプルリクを提出しても良い旨承認いただいています。

2021-08-28 13:28 UTC, shimotaroo requested changes

2021-08-28 13:28 UTC, shimotaroo commented on src/app/Http/Controllers/Auth/RegisterController.php
> +            'term' => ['required', 'digits_between:1,2,numeric']
PSR-2のルールとして、カンマの後には半角スペースが必要です。

2021-08-28 13:28 UTC, shimotaroo commented on src/app/Http/Controllers/Auth/RegisterController.php
>              'password' => ['required', 'string', 'min:8', 'confirmed'],
「半角英数字」であるかどうかのチェックを入れましょう。

https://docs.google.com/spreadsheets/d/1JgDfCq58ptT_GHOkA-uV2AVS2icB38zlHcqJYc8K4A0/edit#gid=597810947

2021-08-28 13:28 UTC, shimotaroo commented on src/resources/views/auth/register.blade.php
> +                                <input type="number" input class="form-control @error('term') is-invalid @enderror" name="term" value="{{ old('term') }}" autocomplete="term" autofocus placeholder="3"
`autofocus`必要でしょうか？？
この属性の役割を調べてみましょう。

2021-08-28 13:28 UTC, shimotaroo commented on src/resources/views/auth/register.blade.php
> +                                <input class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="email" autofocus placeholder="****@mail.com">
autofocus必要でしょうか？？
この属性の役割を調べてみましょう。

2021-08-28 13:28 UTC, shimotaroo commented on src/resources/views/auth/register.blade.php
> +                                <input type="password" input class="form-control @error('password') is-invalid @enderror" name="password" value="{{ old('password') }}" autocomplete="password" autofoc
autofocus必要でしょうか？？
この属性の役割を調べてみましょう。

2021-08-28 13:28 UTC, shimotaroo commented on src/resources/views/auth/register.blade.php
> +                            <input type="password" input class="form-control @error('password-confirm') is-invalid @enderror" name="password_confirmation" value="{{ old('password_confirmation') }}" a
autofocus必要でしょうか？？
この属性の役割を調べてみましょう。

2021-08-28 13:28 UTC, shimotaroo commented on src/routes/web.php
> +Route::post('register', 'Auth\RegisterController@register')->name('register.post');
下の`Auth::routes();`でここで定義しているルーティングはすでに定義されています。

`php artisan route:list`をDockerコンテナ内で実行して定義済みルーティングを確認してみましょう！

上記2つを残すなら21行目は削除してください！
（そのかわりログイン、ログアウトのルーティングも担当者が今回のようにそれぞれ定義する必要があります）

2021-08-28 14:28 UTC, Kataoka-PHP commented on src/app/Http/Controllers/Auth/RegisterController.php
> +            'term' => ['required', 'digits_between:1,2,numeric']
digits以下の部分もカンマの後にスペース必要なんですね
承知しました
ありがとうございます

2021-08-28 14:28 UTC, Kataoka-PHP commented on src/app/Http/Controllers/Auth/RegisterController.php
>              'password' => ['required', 'string', 'min:8', 'confirmed'],
確認不十分でした
失礼しました

2021-08-28 14:29 UTC, Kataoka-PHP commented on src/resources/views/auth/register.blade.php
> +                                <input type="number" input class="form-control @error('term') is-invalid @enderror" name="term" value="{{ old('term') }}" autocomplete="term" autofocus placeholder="3"
すみません
こちら、消し忘れでした

2021-08-28 14:29 UTC, Kataoka-PHP commented on src/resources/views/auth/register.blade.php
> +                                <input class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="email" autofocus placeholder="****@mail.com">
すみません
こちら、消し忘れでした

2021-08-28 14:29 UTC, Kataoka-PHP commented on src/resources/views/auth/register.blade.php
> +                                <input type="password" input class="form-control @error('password') is-invalid @enderror" name="password" value="{{ old('password') }}" autocomplete="password" autofoc
すみません
こちら、消し忘れでした

2021-08-28 14:29 UTC, Kataoka-PHP commented on src/resources/views/auth/register.blade.php
> +                            <input type="password" input class="form-control @error('password-confirm') is-invalid @enderror" name="password_confirmation" value="{{ old('password_confirmation') }}" a
すみません
こちら、消し忘れでした

2021-08-28 14:29 UTC, Kataoka-PHP commented on src/routes/web.php
> +Route::post('register', 'Auth\RegisterController@register')->name('register.post');
ご確認ありがとうございます
`php artisan route:list`はほとんど使ったことなかったので、確認してみます。
ルーティングについては、チームのメンバーとも会話して、21行目を残す形で再提出させていただきます

2021-08-29 00:05 UTC, shimotaroo requested changes

2021-08-29 00:05 UTC, shimotaroo commented on src/app/Http/Controllers/Auth/RegisterController.php
> +            'term' => ['required', 'digits_between:1, 2, numeric']
こちら僕の見落としだったのですが、スペースが必要なのはdigits_betweenとnumericの間です。
が、今はdigits_betweenの第3引数にデータ型を定義されている感じなのですね。
公式ドキュメントにこの書き方が載っていなかったのでこの書き方で文字列を弾けるのであれば問題ないですが、確実にいくならdigits_betweenとnumericは分けてクォーテーションで囲むのが無難かと思います。

[
<img width="723" alt="スクリーンショット 2021-08-29 9 02 07" src="https://user-images.githubusercontent.com/58982088/131233935-3baf4d0d-240b-4905-a5c5-b73320ba9321.png">
](url)

https://readouble.com/laravel/6.x/ja/validation.html

2021-08-29 01:03 UTC, Kataoka-PHP commented on src/app/Http/Controllers/Auth/RegisterController.php
> +            'term' => ['required', 'digits_between:1, 2, numeric']
こちらスペースについての認識を勘違いしていました。
確かに、digits_betweenとnumericは分けて記述する方が統一感あって、わかりやすいです

2021-08-29 04:57 UTC, shimotaroo approved these changes

2021-08-29 04:57 UTC, merged