マイグレーション作成
shimotaroo/Yanbaru-Qiita-App pull request #2
Opened 2021-03-07 04:18 UTC by ks24pon

upメソッドの書き方が、調べながらしたので間違っていることがあると思いますので確認お願いします。

2021-03-07 13:03 UTC, ryota100 commented
お疲れ様です。

基本形はできているかと思います✨
ただ、抜けなどもありますので、それら修正ください。

categoriesテーブルとarticlesテーブルについて、指摘しました。
また、Usersテーブルのマイグレーションファイルについて、カラムがなどが仕様の通り変更されておりませんでしたので、そちら修正ください。

以上、宜しくお願いします。

2021-03-07 13:19 UTC, ryota100 commented on src/database/migrations/2021_03_06_082910_categories_table.php
> +            $table->string('name');
作成はできますが、並び順は仕様書の並びで同じにすると見やすいので、変更しましょう。

2021-03-09 08:23 UTC, ks24pon reviewed
修正しました。お願いします

2021-03-09 14:47 UTC, ryota100 reviewed
お疲れ様です。

確認しました。
外部キー制約の理解が課題なのかなと思いました。
一応補足しましたが、他にも、laravelquestで１対多を作るときにどのように関係性を記述していたか、確認するといいと思います。

主に、外部キー制約について、理解を深めて、もう一度pushいただけたらと思います。
以上、宜しくお願いします。

2021-03-09 14:47 UTC, ryota100 commented on src/database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->foreign('user_id')->references('id')->on('users')->ondelete('cascade');
$table->biginteger('user_id')->unsigned()->nullable();
これはuserテーブルの仕様書に、user_idというカラムはないので必要ありません。
そして、おそらく混乱されているのだと思いますが、
$table->foreign('user_id')->references('id')->on('users')->ondelete('cascade');
この外部キー制約は、どのような意味になるかというと、
usersテーブルのidとuser_idを紐付けるという意味になります。（意味を為してない）
外部キー制約は、他のテーブルのカラムとこのテーブルで指定したカラムを紐づけるものなので、別の場所で使う必要があります。

2021-03-09 14:47 UTC, ryota100 commented on src/database/migrations/2021_03_06_082910_categories_table.php
> +            $table->foreign('user_id')->references('id')->on('users')->ondelete('cascade');
この２行も必要ないです。
この外部キー制約は、
usersテーブルのidとこのテーブルにあるuser_idを紐づけています。
他のテーブルとの紐づけには成功してますが、仕様にはない、紐付けですので、不要な記述になります。

2021-03-09 14:47 UTC, ryota100 commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +            $table->bigIncrements('use_id');
user_idカラムは、ER図にてintで指定されておりますが、bigIncrements（自動増分）では、数値を指定出来ないので、以下も参考にしながら変更しましょう。
以下大事です。

https://readouble.com/laravel/6.x/ja/migrations.html?header=%25E4%25BD%25BF%25E7%2594%25A8%25E3%2581%25A7%25E3%2581%258D%25E3%2582%258B%25E3%2582%25AB%25E3%2583%25A9%25E3%2583%25A0%25E3%2582%25BF%25E3%2582%25A4%25E3%2583%2597

2021-03-09 14:47 UTC, ryota100 commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
>              $table->int('category_id');
intから別の他でも使っている表記にしましょう。

2021-03-09 14:47 UTC, ryota100 commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> -            $table->bigIncrements('id');
bigIncrementsからなるPKは、idなので、これは必要なカラムです。

2021-03-10 13:11 UTC, ks24pon reviewed
修正しました。レビューお願いします。

2021-03-10 13:59 UTC, ryota100 reviewed
お疲れ様です。

かなり仕上がってきてますね！

１点だけ指摘しましたので、そちらだけ確認ください。

(追記)
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->dateTime('deleted_at');
かなしろさんからのseedファイル作成で、見つかりましたが、上の記述は、全てnull値が許容されてないので、

以下から、ぜひ、null値も許容したcreated_atとupdated_atとdeleted_atの書き方を見つけてみてください。(勉強と思って)

https://readouble.com/laravel/6.x/ja/migrations.html?header=%25E3%2582%25AB%25E3%2583%25A9%25E3%2583%25A0%25E4%25BD%259C%25E6%2588%2590

2021-03-10 22:41 UTC, shimotaroo requested changes
レビューしときました！

コメントを確認の上、修正をお願いします！

2021-03-10 22:41 UTC, shimotaroo commented on src/database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->datetime('updated_at');
`$table->timestamps();`を使いましょう！

2021-03-10 22:41 UTC, shimotaroo commented on src/database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->dropForeign('create_users_table');
これは外部キー用の処理になっております。
デフォルトの処理に戻しましょう！

こちらを参考にしてください👇
https://readouble.com/laravel/6.x/ja/migrations.html#renaming-and-dropping-tables

2021-03-10 22:41 UTC, shimotaroo commented on src/database/migrations/2021_03_06_082910_categories_table.php
> +            $table->dateTime('updated_at');
`$table->timestamps();`を使いましょう！

2021-03-10 22:41 UTC, shimotaroo commented on src/database/migrations/2021_03_06_082910_categories_table.php
> +            $table->dropForeign('categories_table');
これは外部キー用の処理になっております。
デフォルトの処理に戻しましょう！

こちらを参考にしてください👇
https://readouble.com/laravel/6.x/ja/migrations.html#renaming-and-dropping-tables

2021-03-10 22:41 UTC, shimotaroo commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +            $table->dateTime('updated_at');
`$table->timestamps();`を使いましょう！

2021-03-10 22:41 UTC, shimotaroo commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +            $table->dateTime('deleted_at');
deleted_atは今回は論理削除用のカラムですのでこちらを参考にしてください👇
https://zenn.dev/shimotaroo/articles/d7c170d55aa1d3

2021-03-10 22:41 UTC, shimotaroo commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +       Schema::dropForeign('create_articles_table');
これは外部キー用の処理になっております。
デフォルトの処理に戻しましょう！

こちらを参考にしてください👇
https://readouble.com/laravel/6.x/ja/migrations.html#renaming-and-dropping-tables

2021-03-11 13:48 UTC, ryota100 commented
お疲れ様です。

２点だけ指摘しました。
後少しです。そちらについて修正ください。

2021-03-11 13:49 UTC, ryota100 approved these changes

2021-03-11 13:49 UTC, ryota100 commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +       Schema::dropsoftdeletes('articles');
Schema::dropsoftdeletes('articles');
ここの書き方も他のところと同じでゆーたろーさんが指摘されたデフォルトの状態に戻す形で大丈夫です

2021-03-11 13:49 UTC, ryota100 commented on src/app/User.php
> +
めちゃくちゃ細かいところですが、余計な改行履歴は無くしておきましょう。

2021-03-12 11:50 UTC, ks24pon commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +       Schema::dropsoftdeletes('articles');
Schema::dropsoftdeletes('articles');を修正しました。
再度レビューお願いします。

2021-03-12 11:51 UTC, ks24pon commented on src/app/User.php
> +
空白の行を無くしました。
再度レビューお願いします！

2021-03-12 14:25 UTC, ryota100 commented
お疲れ様でした！

OK！です。

2021-03-12 15:12 UTC, shimotaroo requested changes
レビューしました！
あともう少しですので頑張ってください！！！

2021-03-12 15:12 UTC, shimotaroo commented on src/database/migrations/2014_10_12_000000_create_users_table.php
> +       Schema::drop('users');
ここ修正する必要がないので戻しておきましょう！

2021-03-12 15:12 UTC, shimotaroo commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +       Schema::drop('articles');
src/database/migrations/2014_10_12_000000_create_users_table.phpの修正に合わせて修正しましょう！

2021-03-12 15:12 UTC, shimotaroo commented on src/database/migrations/2021_03_06_082910_categories_table.php
> +        Schema::drop('categories');
src/database/migrations/2014_10_12_000000_create_users_table.phpの修正に合わせて修正しましょう！

2021-03-12 15:12 UTC, shimotaroo commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +            $table->integer('categories_id')->unsigned()->index();
カラム名が異なります！

2021-03-12 15:12 UTC, shimotaroo commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +            $table->foreign('categories_id')->references('id')->on('categories')->onDelete('cascade');
カラム名が異なります！

2021-03-13 05:25 UTC, ks24pon commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +            $table->integer('categories_id')->unsigned()->index();
カラム変更しました！
レビューお願いします。

2021-03-13 05:25 UTC, ks24pon commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +            $table->foreign('categories_id')->references('id')->on('categories')->onDelete('cascade');
修正しました。
再度レビューお願いします。

2021-03-13 05:26 UTC, ks24pon commented on src/database/migrations/2014_10_12_000000_create_users_table.php
> +       Schema::drop('users');
修正しました。
再度レビューお願いします。

2021-03-13 05:27 UTC, ks24pon commented on src/database/migrations/2021_03_06_082910_categories_table.php
> +        Schema::drop('categories');
Schema::dropIfExists('categories');に変更しました！
レビューお願いします。

2021-03-13 05:41 UTC, ks24pon commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +       Schema::drop('articles');
Schema::dropIfExists('articles');に変更しました！
レビューお願いします。

2021-03-13 11:31 UTC, ks24pon reviewed
修正しました。
お願いします。

2021-03-13 14:55 UTC, shimotaroo requested changes
レビューしました！

共同開発全体の進捗にも影響するので、本来は望ましくないのですが答えをコメントしていますのでその通りに修正して再度pushしてください🙇‍♂️

2021-03-13 14:55 UTC, shimotaroo commented on src/database/migrations/2014_10_12_000000_create_users_table.php
> +       Schema::dropIfExists('articles');
これは不要です！消しましょう！

2021-03-13 14:55 UTC, shimotaroo commented on src/database/migrations/2021_03_06_082910_categories_table.php
> +        Schema::dropIfExists('articles');
これは不要です！消しましょう！

2021-03-13 14:55 UTC, shimotaroo commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +            $table->integer('categories_id')->unsigned()->index();
@ks24pon 

```
$table->integer('category_id')->unsigned()->index();
```

に変更してください！

ER図をしっかり見ましょう！！

2021-03-13 14:55 UTC, shimotaroo commented on src/database/migrations/2021_03_06_083426_create_articles_table.php
> +            $table->foreign('categories_id')->references('id')->on('categories')->onDelete('cascade');
@ks24pon 

```
$table->foreign('category_id')->references('id')->on('categories')->onDelete('cascade');
```

に変更してください！

2021-03-13 15:10 UTC, shimotaroo approved these changes
マージします！
お疲れ様でした！！

2021-03-13 15:10 UTC, merged