記事削除機能＠10-B-なみき
shimotaroo/Yanbaru-Qiita-App pull request #203
Opened 2021-09-12 12:02 UTC by nachi739

##変更目的
記事の削除機能の追加

##変更内容
routes/web.php 
　インデント修正
　routeにdestroy追加
resources/views/layouts/app.blade.php
　記事投稿の遷移先追記
resources/views/articles/show.blade.php
　ボタンのみ追加（遷移先未指定）
resources/views/articles/index.blade.php
　削除機能追加
app/Http/Controllers/ArticlesController.php 
　処理先の指定
##変更によって期待される結果と動作確認
記事一覧画面からの記事削除（論理削除）

##未作成
記事詳細画面からの削除
記事詳細タスク完了後に追記のため

2021-09-12 14:42 UTC, shimotaroo requested changes

2021-09-12 14:42 UTC, shimotaroo commented on src/resources/views/articles/show.blade.php
> +                                <form action="" class="col-md-3 p-0 row mx-1"> {{--記事詳細画面後に処理追記--}}
actionはこの時点で設定できるので設定しておきましょう！

2021-09-12 14:42 UTC, shimotaroo commented on src/resources/views/articles/index.blade.php
> +                                        <form action="{{ route('articles.destroy', $article->id) }}" method="POST" id="delete-form">
destroyメソッドの引数のタイプヒンティングでArticleを指定するのであればここはidを渡さずにArticleモデルのインスタンスごと渡してあげましょう！
（少し考えて修正してみてください）

2021-09-12 17:13 UTC, nachi739 commented on src/resources/views/articles/index.blade.php
> +                                        <form action="{{ route('articles.destroy', $article->id) }}" method="POST" id="delete-form">
上記の点修正致しましたので
ご確認の程宜しくお願い致します
actionはまだ設定出来ていないです

2021-09-13 06:43 UTC, nachi739 commented
actionの設定の際view表示でのエラーは解決しました。
詳細画面がまだ出来ていないのでボタンを押すとエラー発生しないように変更
$articleが未定義のエラーのため発生しないように一時的に変更しました。

2021-09-13 12:38 UTC, shimotaroo approved these changes
LGTM

2021-09-13 12:38 UTC, merged