CategoriesTableのシーダーファイル作成（若松）
shimotaroo/Yanbaru-Qiita-App pull request #23
Opened 2021-04-12 12:32 UTC by ai-wakamatsu

Categoriesテーブルのシーダーファイルを作成しましたので、ご確認をよろしくお願いいたします。

2021-04-12 21:58 UTC, miki-mitsuki approved these changes
きれいにコード書けていると思います。
1点気になった点コメントしていますので、確認いただければと思います。

2021-04-12 21:58 UTC, miki-mitsuki commented on src/app/Category.php
> +<?php
Category.phpというモデルを作成されていますが、タスクの内容には含まれていないのでこのPRには含めない方がよいです。

2021-04-13 00:03 UTC, shimotaroo requested changes
全体的によく出来ていますね👍
1点だけ修正して欲しいところがあるのでコメントさせていただきました！！

2021-04-13 00:03 UTC, shimotaroo commented on src/database/seeds/CategoriesTableSeeder.php
> +          ['name' => 'Ruby'],
それぞれのデータの

- created_at
- updated_at

カラムの値が入ってないですね。。追記しましょう！！

シーダーファイルには基本的にテーブルに存在するカラムは全て書きます！
例えば、NULLを許容している仕様のカラムでも
```
`column` => null,
```
こんな感じで書くべきです！

2021-04-13 04:53 UTC, ai-wakamatsu commented on src/app/Category.php
> +<?php
まさに、後で使うと思って作っていました。今後はタスクが混同しないように気をつけます！

2021-04-13 04:55 UTC, ai-wakamatsu commented on src/database/seeds/CategoriesTableSeeder.php
> +          ['name' => 'Ruby'],
nullのカラムでも全て書くものなんですね！勉強になります。

2021-04-13 04:57 UTC, ai-wakamatsu commented
シーダーファイルを修正しましたのでご確認をお願いします！

2021-04-13 07:47 UTC, shimotaroo approved these changes
レビューしました！
LGTMです😆
お疲れ様でした！

2021-04-13 07:47 UTC, shimotaroo commented on src/database/seeds/CategoriesTableSeeder.php
> +          ['name' => 'Ruby', 'created_at' => null, 'updated_at' => null],
連想配列は以下の様に1行に1項目書くのが一般的なので今後意識してください！

```
[
    'name' => 'Laravel',
    'created_at' => null,
    'updated_at' => null
],
```

あと、`'id'`も入っていた方がよりわかりやすいなと思いますが、問題なくシーダーファイルを実行できていると思うのでOKです！

2021-04-13 07:47 UTC, merged