Feature/suzuki/create seeder file 1
shimotaroo/Yanbaru-Qiita-App pull request #24
Opened 2021-04-14 05:25 UTC by ysuzuki336

2021-04-14 15:18 UTC, yoshitaro-yoyo commented on src/app/Article.php
> +
複数のモデルを作成されていますが、今回のタスクの内容には含まれていないのでこのPRには含めない方がよいです。
シーダーファイル作成のタスクなのでそれ以外のことは違うブランチを切って別にPRを発行するようにしましょう！

2021-04-14 15:20 UTC, yoshitaro-yoyo commented on src/app/Article.php
> +<?php
PR名ですが、6期生のアナウンススレッドでお知らせしたように以下の書き方で統一お願いします！

>PR作成時ですが、PR名に名前と何をどうしたのか書いて下さい:pray::skin-tone-2:
ぱっと見て誰が何をしたのか解るようにして貰えると管理しやすいです!
以下を参考にお願いします！
<img width="543" alt="スクリーンショット 2021-04-11 13 06 15" src="https://user-images.githubusercontent.com/69310368/114735595-4ee5f480-9d80-11eb-83ce-6c5ef019612f.png">

2021-04-14 15:22 UTC, yoshitaro-yoyo commented on src/app/User.php
> +        'name', 'email', 'password', 'term'
素晴らしい気付きですね！

2021-04-14 15:25 UTC, yoshitaro-yoyo commented on src/app/User.php
> +    }
ここの記述方法はリファレンスに有るような記述方法に統一しましょう！
https://readouble.com/laravel/5.8/ja/eloquent-relationships.html

2021-04-14 15:27 UTC, yoshitaro-yoyo commented on src/app/User.php
> +        return $this->hasMany(Comment::class);
こちらのModelの指定方法も上記に沿って変更しましょう！

2021-04-14 15:28 UTC, yoshitaro-yoyo commented on src/database/migrations/2014_10_12_000000_create_users_table.php
>      {
こちらもタスクとして別なのでブランチやPRを分けましょう！

2021-04-14 15:52 UTC, yoshitaro-yoyo commented on src/database/seeds/ArticlesTableSeeder.php
> +    {
ER図を見るとカラムが足りませんね
<img width="281" alt="スクリーンショット 2021-04-15 0 51 25" src="https://user-images.githubusercontent.com/69310368/114740387-c453c400-9d84-11eb-917a-40373cca6ca9.png">

2021-04-14 15:54 UTC, yoshitaro-yoyo commented on src/database/seeds/CategoriesTableSeeder.php
> +    public function run()
じょうきと上記と同様ですね！
<img width="288" alt="スクリーンショット 2021-04-15 0 53 56" src="https://user-images.githubusercontent.com/69310368/114740741-17c61200-9d85-11eb-9224-f097458dc9c8.png">

2021-04-14 15:56 UTC, yoshitaro-yoyo commented on src/database/seeds/DatabaseSeeder.php
> +        $this->call(CommentsTableSeeder::class);
こちらの
`$this->call`
の記述は全部で一度で済むように、配列を用いて記述しましょう

2021-04-14 16:08 UTC, yoshitaro-yoyo commented on src/database/seeds/UsersTableSeeder.php
> +            'password' => bcrypt('satou123'),
がめんて画面定義書で指定されている仕様に下記のような記述があります。
パスワードの文字数が8文字以上のバリデーションをかけていますので全て8文字以上に変更しましょう
<img width="575" alt="スクリーンショット 2021-04-15 1 03 57" src="https://user-images.githubusercontent.com/69310368/114742268-88b9f980-9d86-11eb-87ba-7d7428b5534e.png">

またLaravelではハッシュ化する時は

```
Hash:make()
```
を使うのがマニュアルにも記載されていますので、今後は

2021-04-14 16:28 UTC, yoshitaro-yoyo commented on src/database/seeds/ArticlesTableSeeder.php
> +        DB::table('articles')->insert([
`DB::table('articles')->insert([`
の記述も配列形式で記述すると一度の記述で済みます！

`
[
-----
],
[
-----
]
`
の様に1レコードずつ`[]`で区切ってみて下さい☺️

2021-04-14 16:40 UTC, yoshitaro-yoyo reviewed
コメントと修正点、結構多いので確認お願いします🤣
多くのタスクをこなしていて大変だと思います！
私も沢山指摘され大変でした（笑）
意味が解らない所もあるかもしれませんがその際はいつでも質問してくださいね！

2021-04-14 16:45 UTC, yoshitaro-yoyo reviewed
コメントと修正点、結構多いので確認お願いします🤣
多くのタスクをこなしていて大変だと思います！
私も沢山指摘され大変でした（笑）
意味が解らない所もあるかもしれませんがその際はいつでも質問してくださいね！

2021-04-15 02:09 UTC, ysuzuki336 commented on src/app/Article.php
> +
シーダーファイ作成にあたってシーダーが正常に実行されることを確認するために、マイグレーションファイルとモデルも作成しました。シーダーは実行せずシーダーファイルのみ作成し、PRを発行すると言うことでしょうか。

2021-04-15 03:29 UTC, ysuzuki336 commented on src/database/migrations/2014_10_12_000000_create_users_table.php
>      {
自分の認識に誤りがあり、シーダーファイル作成は実行まで行うものと思っていたので仮としてマイグレーションファイルも作成しました。すいません。
コードレビューをいただいた訂正を含め、develop-6th-macから再度pullし、シーダーファイル作成することになりました。
この作業内容でよろしかったでしょうか。

2021-04-17 06:54 UTC, yoshitaro-yoyo reviewed
お疲れさまです。いくつか修正点がありますのでご確認お願いします！

2021-04-17 06:54 UTC, yoshitaro-yoyo commented on src/routes/web.php
> +
この２行は消しましょう！自分もよくやるんですが…笑
push前に確認してpushしないようにしましょう！

2021-04-17 06:54 UTC, yoshitaro-yoyo commented on src/database/seeds/UsersTableSeeder.php
> +            'password' => Hash::make('satou123'),
バッチリです！

2021-04-17 06:54 UTC, yoshitaro-yoyo commented on src/database/seeds/UsersTableSeeder.php
> +            'updated_at' => now(),
不足カラムの追加や記述の順番もOKです！

2021-04-17 06:54 UTC, yoshitaro-yoyo commented on src/database/seeds/UsersTableSeeder.php
> +        [
配列での記述もオッケーですね！素晴らしい✨

2021-04-17 06:54 UTC, yoshitaro-yoyo commented on src/database/migrations/2021_04_14_045014_create_articles_table.php
> +<?php
今回作成したMigartionファイルは全て削除して下さい。
リモートリポジトリのdevelopブランチを、ローカルリポジトリのdevlopブランチにpullして現在suzukiさんが作業中のブランチとマージして下さい！さすれば作業中のブランチにkazuさんが作成したマイグレーションファイルが反映されます。但し、注意点等も多いのでゆーたろーさんの資料を確認したり調べながら実行してみて下さい。

解らなかったら聞いてくださいね👍

2021-04-17 06:54 UTC, yoshitaro-yoyo commented on src/database/seeds/DatabaseSeeder.php
> +        foreach($items as $item) {
面白い書き方ですね！
ここも下記の様な配列形式記述でも可能です。
ループ処理は余り一般的ではないと思いますが、りょうたさんに確認してもらいましょうか🤔

2021-04-17 06:54 UTC, yoshitaro-yoyo commented on src/app/Article.php
> +
マイグレーションファイルのレビューに返答を記載してますのでそちらで確認して下さい

2021-04-17 07:45 UTC, ysuzuki336 commented
マイグレーションファイルの削除、web.phpの不要な行の削除をしましたのでご確認よろしくお願い致します。

2021-04-17 13:59 UTC, yoshitaro-yoyo commented on src/routes/web.php
> +});
オッケーですが、マイグレーションファイル 削除出来てないようです！
もう一度ご確認お願いします！

2021-04-18 15:05 UTC, ryota100 reviewed
お疲れ様です。

基本OKです！
２点指摘しましたので、そちらについて修正お願いします。

2021-04-18 15:05 UTC, ryota100 commented on src/config/database.php
> +            'password' => env('DB_PASSWORD', 'yuta'),
これは、git上に
DB_DATABASE
DB_USERNAM
DB_PASSWORD
を第二候補として公開することになるので、ここは元に戻して、
記載が必要ならgit上で公開されない.envファイルに上の内容は書くようにしましょう。

2021-04-18 15:05 UTC, ryota100 commented on src/database/seeds/DatabaseSeeder.php
> +        foreach($items as $item) {
php artisan db:seedを利用すると正常にサンプルデータが作成されなかったので、記載方法を変更しましょう。
一例として、以下のような配列型式があります。
$this->call([
UsersClassificationsTableSeeder::class,
UsersTableSeeder::class,
T_OrdersTableSeeder::class,
M_CategoriesTableSeeder::class,
M_Sales_StatusesTableSeeder::class,
M_Products_StatusesTableSeeder::class,
M_ProductsTableSeeder::class,
]);

2021-04-19 07:43 UTC, yoshitaro-yoyo reviewed
もう少しです！
頑張りましょう🤣

2021-04-19 07:43 UTC, yoshitaro-yoyo commented on src/database/seeds/DatabaseSeeder.php
> +            ]);
14行目のインデント、13行目に対して多すぎませんか？
15行目のインデント、14行目に対して少ないです！
コード規約を意識しましょう。
PRする前に間違っていないか確認してから push する癖をつけましょう！

2021-04-19 07:43 UTC, yoshitaro-yoyo commented on src/config/database.php
> +            'password' => env('DB_PASSWORD', ''),
こちらを削除後でもDBとの接続が可能だったか確認はしてますか？
以前繋がらなくてこちらの記述を追加した経緯があったかと思いますが🤔

2021-04-19 11:09 UTC, ysuzuki336 commented on src/config/database.php
> +            'password' => env('DB_PASSWORD', ''),
接続確認できました。

2021-04-19 11:16 UTC, yoshitaro-yoyo commented on src/database/seeds/DatabaseSeeder.php
> -            ]);
バッチリですね！こういった記述の構造には違和感をおぼえるようにしておきましょう😁

2021-04-19 11:17 UTC, yoshitaro-yoyo commented on src/database/seeds/DatabaseSeeder.php
> +        ]);
バッチリですね！こういった記述の構造には違和感をおぼえるようにしておきましょう😁

2021-04-19 13:26 UTC, shimotaroo requested changes
レビューしました！
1点だけコメントしていますので修正お願いします！

2021-04-19 13:26 UTC, shimotaroo commented on src/config/database.php
> +            'username' => env('DB_USERNAME', ''),
ここの修正は不要かと思いますので戻しておいてください！

2021-04-20 05:24 UTC, shimotaroo approved these changes
LGTMです😁
マージします！

マージするのですが、以下のアドバイスをさせていただきますので頭に入れておいてください。

- 今回はシーダーファイル作成のPRなのでモデルの作成は不要でした。1つのブランチでの開発でどのファイルを追加するのかは考える必要があります。
- 最後のコミットメッセージが「シーダーファイルの修正」になっていますが、シーダーファイルは修正してないかと思います。コミットメッセージは適切につけつけるように意識してみましょう。

2021-04-20 05:24 UTC, merged