記事投稿画面作成（王）
shimotaroo/Yanbaru-Qiita-App pull request #34
Opened 2021-04-19 14:25 UTC by yuqi1020

記事投稿画面の作成が完了しましたので、ご確認お願い致します。

2021-04-19 15:55 UTC, miki-mitsuki reviewed
インデントなどがしっかり使われておりきれいにコード書けていると思います。
機能面で何点かレビューしていますのでご確認お願いいたします。

2021-04-19 15:55 UTC, miki-mitsuki commented on src/app/Http/Controllers/ArticlesController.php
> +            'category_id' => 'required|size:1',
画面設計書ではカテゴリーのバリデーションは
`必須、文字列、1文字`となっていますので、文字列であるかどうかも確かめていただきたいです。

2021-04-19 15:55 UTC, miki-mitsuki commented on src/resources/views/articles/create.blade.php
> +                                @error('title')
エラーメッセージが`titleを入力してください。`のように一部英語で表示されていますので、すべて日本語で表示されるよう修正していただけますでしょうか？
（ほかのバリデーションエラーのメッセージも同様です）

2021-04-20 12:30 UTC, yuqi1020 commented
お疲れ様です。
ご指摘箇所の修正が完了しましたので、ご確認お願い致します。
修正箇所は下記の通りです。

- 文字列バリデーション追加
- バリデーション日本語化
- バリデーションエラーになった場合、直前に入力した値をフォームに保持できるよう修正

2021-04-20 20:24 UTC, miki-mitsuki approved these changes
修正概ね問題ないです。
1点修正方法に関してレビュー追記していますのでご確認いただければと思います。

2021-04-20 20:24 UTC, miki-mitsuki commented on src/resources/lang/ja/validation.php
> +    'accepted' => '承認してください。',
:attributeを削除してくださってくださっていますが、本来は:attributeが日本語に変換されるように処理を書いた方がよいです。
(同ファイル内の`'attributes' => [`で設定できます)
今回は削除していても意味が通るため、このままで問題ありません。

2021-04-20 23:46 UTC, shimotaroo requested changes
レビューしました！
数点コメントしましたのでご確認お願いします！

2021-04-20 23:46 UTC, shimotaroo commented on src/resources/lang/ja/validation.php
> +    'accepted' => '承認してください。',
Mikiさんのコメント通り、`:attributes`は削除しない方が良いですね。

2021-04-20 23:46 UTC, shimotaroo commented on src/app/Http/Controllers/ArticlesController.php
> +        ]);
Laravelのドキュメントにあるバリデーション実装方法には
```
$this->validate
```
のようにコントローラーが持っているメソッドで実装する方法は書かれていませんが、どのような記事をみながら実装されましたか？

https://readouble.com/laravel/6.x/ja/validation.html

こちらの記事にver5.4以前ではコントローラーメソッドで呼び出していたと書かれており、それが今でも動く（というより動いてしまっている）のではないかと思います。

https://qiita.com/kd9951/items/e797b17c03fc8e8f414b

本来はそのバージョンにあった実装方法で実装するのがベストなので一度背景を教えて欲しいです！

2021-04-21 02:04 UTC, yuqi1020 commented
お疲れ様です。
ご指摘箇所の修正が完了しましたので、ご確認お願い致します。
修正箇所は下記の通りです。

- :attributes復元
- フォームリクエスト追加

2021-04-21 02:46 UTC, yuqi1020 commented
コンフリクトが起きていたので、修正対応しました。

2021-04-21 05:45 UTC, shimotaroo approved these changes
LGTMです😁

フォームリクエストの使い方もバッチリです！

2021-04-21 05:45 UTC, merged