マイページ作成（王）
shimotaroo/Yanbaru-Qiita-App pull request #35
Opened 2021-04-21 09:22 UTC by yuqi1020

お疲れ様です。
マイページ画面の作成が完了しましたので、ご確認をお願いいたします。

2021-04-21 20:44 UTC, miki-mitsuki reviewed
コードの書き方、機能面ともに問題ないと思います。
素晴らしいです！

2021-04-21 20:49 UTC, miki-mitsuki approved these changes
コードの書き方、機能面ともに問題ないと思います。
素晴らしいです！

2021-04-21 23:40 UTC, shimotaroo requested changes
レビューしました！

マイページはURLにユーザーIDが入らない仕様にするよう画面定義所（エクセル）に書いています（先日変更かけました）が、今の仕様だと`/user/2`のようにIDが入ってしまっています。

エクセルを参考にして実装方法を変えてみてください！
<img width="834" alt="スクリーンショット 2021-04-22 8 37 06" src="https://user-images.githubusercontent.com/58982088/115635168-0f05ab00-a346-11eb-8973-5a7916514da0.png">

2021-04-22 03:38 UTC, yuqi1020 commented
ご指摘箇所の修正が完了しましたので、ご確認お願い致します。

2021-04-22 12:32 UTC, shimotaroo approved these changes
LGTMです👌
お疲れ様でした！！！

2021-04-22 12:32 UTC, shimotaroo commented on src/app/Http/Controllers/UserController.php
> +        $articles = $user->articles()->orderBy('id', 'desc')->paginate(5);
マイページの仕様としては

- 並び替え
- ページネーション

は入ってないのでそのユーザーの記事は`$user->articles`で取得できます。

ただ、今回のコードでも大きく問題ないのでOKです！

2021-04-22 12:32 UTC, merged