CSVダウンロード機能実装（王）
shimotaroo/Yanbaru-Qiita-App pull request #40
Opened 2021-04-25 13:49 UTC by yuqi1020

CSVダウンロード機能の実装が完了しましたので、ご確認お願い致します。

2021-04-26 14:36 UTC, shimotaroo requested changes
レビューしました！！
いやあ...さすが素晴らしいですね😁

Mikiさんレビューがあればそれも加味して修正してください！

2021-04-26 14:36 UTC, shimotaroo commented on src/app/Http/Controllers/CsvController.php
> +use Illuminate\Support\Facades\DB;
DBファサードを使っている箇所が見当たらなかったのでこの1行は不要かと思います。
まあ、処理には影響しないので修正しなくてもOKです。

2021-04-26 14:36 UTC, shimotaroo commented on src/app/Http/Controllers/CsvController.php
> +    public function download(Request $request)
- Controller
- メソッド

の命名、ともにグッドだと思います！

2021-04-26 14:36 UTC, shimotaroo commented on src/app/Http/Controllers/CsvController.php
> +        $articles = Article::all();
ここ、

- 記事を投稿したユーザー
- 記事のカテゴリー

がリレーションメソッドによって自動的に取得されるのですが、このままだとN+1問題が発生してしまいます。

「Laravel N+1問題」や「Laravel Eagerローディング」とかでググってみてN+1問題が発生しない書き方にしてみてください。

2021-04-26 14:36 UTC, shimotaroo commented on src/app/Http/Controllers/CsvController.php
> +            $array = array('名前', 'カテゴリー', 'タイトル', '概要', 'URL');
- `$array`だと「何」の配列なのかがわからないので命名してみましょう
- これまで連想配列は`[ ]`で書いていたと思うので揃えましょう。

2021-04-26 14:36 UTC, shimotaroo commented on src/app/Http/Controllers/CsvController.php
> +                $array = array($userName, $categoryName, $article->title, $article->summary, $article->url);
上記コメント同様。

2021-04-26 14:36 UTC, shimotaroo commented on src/app/Http/Controllers/CsvController.php
> +                $array = array($userName, $categoryName, $article->title, $article->summary, $article->url);
`$userName`、`$categoryName`は1度しか使ってないのでわざわざ変数定義せずに

```
$array = [
    $article->user->name,
    $article->category->name,
    $article->title,
    $article->summary,
    $article->url
];
```
これで良いと思いますよ！

2021-04-26 15:02 UTC, miki-mitsuki requested changes
とても素晴らしいと思います！
少しだけ気になった点コメントしていますので、ご確認いただければと思います。

2021-04-27 02:52 UTC, yuqi1020 commented
お疲れ様です。
ご指摘箇所の修正が完了しましたので、ご確認お願い致します。
修正箇所は以下の通りです、

- N＋１問題
- 変数名変更
- 配列の書き方統一

2021-04-27 14:17 UTC, miki-mitsuki approved these changes
確認しました。
修正いただいた箇所問題ないと思います。
変数がどういった意味があるものかわかりやすくなっていて素晴らしいです。

2021-04-28 10:58 UTC, shimotaroo approved these changes
LGMTです😁
マージします！！
お疲れ様でした！！

2021-04-28 10:59 UTC, shimotaroo commented
コンフリクトしていました...！！

2021-04-28 11:24 UTC, yuqi1020 commented
コンフリクト解消しましたので、ご確認お願い致します。

2021-04-29 06:15 UTC, merged