投稿画面の作成
shimotaroo/Yanbaru-Qiita-App pull request #57
Opened 2021-05-18 11:17 UTC by kzri4

【追加】
- ```ArticleController.php```に```create```, ```store```メソッドの記載
-  ```ArticleRequest.php``` の作成
-  ```create.blade.php```の作成

【変更】
- ```Article.php```の```user_id```が不要だったため削除
- ```header.blade.php```の```投稿する```のルーティングを追加

【特記事項】
-  特になし

【仕様抜粋】
- カテゴリーのラジオボタンは「Laravel」「PHP」「Docker」「Web基礎」の4つとする -> OK
- 画面遷移時に「記事タイトル」入力フォームにフォーカスされた状態にする -> OK
- バリデーションがエラーになった場合は投稿画面にリダイレクトする -> OK
- バリデーションエラーになった場合は直前に入力した値をフォームに保持する -> OK
- バリデーションメッセージは各フォームの下に表示する  -> OK
- バリデーションメッセージは日本語で表示する -> OK
- 記事投稿成功後は記事一覧画面にリダイレクトする > OK

2021-05-18 14:16 UTC, yoshitaro-yoyo reviewed
オッケーです！一点だけコメントありますので確認お願いします😁

2021-05-18 14:16 UTC, yoshitaro-yoyo commented on src/app/Http/Requests/ArticleRequest.php
> +    {
この挑戦、最高です👍
ただ適用してます？？
もし、適用方法わからなければ聞いて下さいね！

2021-05-18 23:22 UTC, shimotaroo requested changes
レビューしました！
全体的に良くできているのではないかと思います😁

2021-05-18 23:22 UTC, shimotaroo commented on src/app/Http/Requests/ArticleRequest.php
> +    {
このコメント、どういう意味だろう...？

2021-05-18 23:22 UTC, shimotaroo commented on src/resources/views/articles/create.blade.php
> +                            <input type="radio" name="category_id" value="4">web基礎
記事投稿時のバリデーションに引っかかった時にこのラジオボタンの選択って保持できていますか？
（多分できてないと思われます）

できるようにしましょう！！

2021-05-19 08:14 UTC, yoshitaro-yoyo commented on src/app/Http/Requests/ArticleRequest.php
> +    {
Controllerでのネームスペースの宣言が抜けてるかと思っていましたが、書いてたので自分の勘違いです😂
失礼しました！

2021-05-20 01:13 UTC, kzri4 commented on src/resources/views/articles/create.blade.php
> +                            <input type="radio" name="category_id" value="4">web基礎
【追加】
- ```create.blade.php```にラジオボタン選択保持機能の追加

【変更】
- なし
 
【特記事項】
- なし

2021-05-20 01:13 UTC, kzri4 commented
【追加】
- ```create.blade.php```にラジオボタン選択保持機能の追加

【変更】
- なし
 
【特記事項】
- なし

2021-05-20 10:55 UTC, yoshitaro-yoyo reviewed
確認しました！オケーです！
ただConflictが起きています！
一旦、リモートリポジトリの develop brunch をローカルにpullしてConflict 解消しましょう！
その後に再度pushして下さい👍

解らなかったら聞いてくださいね😁

2021-05-20 13:03 UTC, yoshitaro-yoyo reviewed
何回も申し訳ないです！
もう一点修正と、私のミスの修正の1点の計2点についてコメントしてます。
すみませんがお願いします🙇

2021-05-20 13:03 UTC, yoshitaro-yoyo commented on src/routes/web.php
> +Route::resource('articles', 'ArticleController', ['only' => ['show']]);
16行目と22行目が同じ記述です！22行目を消しましょう！

今回は問題ないのですがルーティングの順番によってはエラー出ます
後学の参考に記事貼っておきますので時間有るときにでもどうぞ😊
[Laravelのルーティング優先度でつまづいた話](https://qiita.com/dhiki1234/items/dcb2d2bc17d11e1f4565)

あと20行目の記述、私が作成した部分ですがここをいかに変更してもらっていいですか？
ユーザ情報はログイン済みのユーザにしか見えないようにすべきでした…😂
```
Route::get('/user', 'UserController@show')->name('user.show')->middleware('auth');
```

2021-05-20 13:57 UTC, shimotaroo approved these changes
LGTMです👍
お疲れ様でした🎉
コーディング規約もバッチリ準拠できていて良いですね！

1点だけ、よりベターな実装にするためのアドバイスを書いていますので確認ください！

2021-05-20 13:57 UTC, shimotaroo commented on src/resources/views/articles/create.blade.php
> +                            <input type="radio" name="category_id" value="4" {{ old('category_id') == 4 ? 'checked': '' }}>web基礎
ここは1つ1つベタ書きするのではなく、ベストは

1. Controllerでカテゴリーテーブルからデータを取得
2. Controllerからbladeにデータを渡す
3. bladeでforeachを使ってラジオボタンを作成する

です。

今の実装だと、仮にテーブルのカテゴリーが増えてしまうとその度にbladeの修正が必要になります！

今回はこのままで大丈夫です！

参考までにHerokuにデプロイしているアプリのソースを貼ります。31行目付近が上記の実装です。
https://github.com/shimotaroo/Yanbaru-Qiita-App-sample/blob/main/resources/views/articles/create.blade.php

2021-05-20 13:57 UTC, merged