ヘッダー（ログイン前）作成
shimotaroo/Yanbaru-Qiita-App pull request #61
Opened 2021-05-21 02:06 UTC by mitsumasaanan

ヘッダー（ログイン前）作成しました。

以下変更項目の詳細です：
・routesのwed.phpにappへのルーティングを記述
・viewsにcommonsフォルダ作成
・commonsフォルダ内にheader.blade.php作成
・public直下にcssフォルダ作成
・cssフォルダ内にapp.css作成
・views内にapp.blade.phpファイルを作成(ヘッダー共有化とcss確認用のページです)

2021-05-21 13:52 UTC, shimotaroo requested changes
レビューしました！

また、以下の不要なファイルが作成されてしまっているので削除お願いします！

- src/public/.DS_Store
- src/.DS_Store
- src/resources/.DS_Store
- src/resources/views/.DS_Store

2021-05-21 13:52 UTC, shimotaroo commented on src/routes/web.php
> +    return view('app');
ルーティングはURLとコントローラーのメソッドを対応づける書き方に変更しましょう！
以下のドキュメントの「デフォルトルート定義ファイル」の書き方が一般的です！
https://readouble.com/laravel/6.x/ja/routing.html

2021-05-23 08:41 UTC, mitsumasaanan commented on src/routes/web.php
> +    return view('app');
不要なファイル(.DS_Store)の削除と、ルーティング記述方法の変更を致しました。
ご確認よろしくお願いします。
（次回のプルリクから上記ブランチ名の命名規則に沿ったプルリクを出すように致します。）

2021-05-23 13:14 UTC, shimotaroo requested changes
レビューしましたのでご確認お願いします！
1点だけ修正お願いします！

2021-05-23 13:14 UTC, shimotaroo commented on src/resources/views/commons/header.blade.php
> +            <a class="navbar-brand site-logo" href="/">Yanbaru Qiita</a>
`href="/"`の記述ですが、Laravelではaタグでリンクを作る時はurl()もしくはroute()を使います。
（route()を使うことが多いです）

公式ドキュメントはこちらです👇
https://readouble.com/laravel/6.x/ja/urls.html

2021-05-23 13:14 UTC, shimotaroo commented on src/app/Http/Controllers/UserController.php
> +}
`/`に対応する画面ははユーザー情報ではなく記事一覧画面です！

なので`UserController`ではなく`ArticleController`にしましょう。

2021-05-25 07:06 UTC, mitsumasaanan commented on src/resources/views/commons/header.blade.php
> +            <a class="navbar-brand site-logo" href="/">Yanbaru Qiita</a>
hrefの記述修正致しました。ご確認宜しくお願い致します。

2021-05-25 07:06 UTC, mitsumasaanan commented on src/app/Http/Controllers/UserController.php
> +}
UserControllerからArticleControllerに修正致しました。ご確認宜しくお願い致します。

2021-05-25 12:18 UTC, shimotaroo approved these changes
LGTMです😁
お疲れ様でした！

2021-05-25 12:18 UTC, merged