WIP:記事投稿機能
shimotaroo/Yanbaru-Qiita-App pull request #76
Opened 2021-06-03 14:47 UTC by shingo-suzumura

【追加点】
・`ArticleRequest`の作成とバリデーション。
・`ArticleController`にstore処理の追加。
・`create.blade.php`にエラー表示箇所を追加。

現時点ではユーザー機能が未実装のため、コントローラもユーザ認証を通さず投稿機能のみ記述しました。
ユーザー機能が実装され次第追記します。

2021-06-04 12:15 UTC, shimotaroo requested changes
ラジオボタンのチェック保持、とても素晴らしいです！
よくできましたね😁

いくつかレビューしていますので修正お願いします！

2021-06-04 12:15 UTC, shimotaroo commented on src/app/Http/Requests/ArticleRequest.php
> +            'category_id' => 'required|string|',
1文字しか受け付けないバリデーションが抜けているのでつけてみましょう！

2021-06-04 12:15 UTC, shimotaroo commented on src/app/Http/Requests/ArticleRequest.php
> +            'summary' => 'required|string|max:30',
ここもバリデーション内容が異なるので探してみましょう！

2021-06-04 12:15 UTC, shimotaroo commented on src/app/Http/Requests/ArticleRequest.php
> +            'url.url' => 'Qiita記事の:attributeを入力してください。'
バリデーションは個別に設定していくとかなり大変＆他のバリデーションでも同じように全てのメッセージを定義しないといけなくなるので、言語ファイルを準備しましょう！

こちらの記事
https://qiita.com/samuraibrass/items/d71c08e144dbbf98e348
や
公式ドキュメント
https://readouble.com/laravel/6.x/ja/validation-php.html
を活用して

messages()を使わない方法で実装してみましょう！（その代わりattributes()が必要になります）

2021-06-04 12:15 UTC, shimotaroo commented on src/app/Http/Controllers/ArticleController.php
> +        return redirect()->route('app');
ここは処理には影響しない＆投稿処理の範囲外ですが、`app`でトップページということがわかりにくいです。（わかりにくくないですか？笑）

トップページは`index`、`top`を使うことが多いのでこの機会に修正してみてください！

2021-06-05 06:37 UTC, shingo-suzumura commented
【変更点】
・日本語の言語ファイルを追加。
・`validation.php`にattributesを追記、コントローラーからmessageとattributesを削除。
・トップページの名称変更。
・バリデーションの修正。

2021-06-05 23:52 UTC, shimotaroo approved these changes
LGTM！！

バッチリです😁
素晴らしいです！
この調子でどんどん進めてください！

2021-06-05 23:52 UTC, shimotaroo commented on src/app/Http/Requests/ArticleRequest.php
> +            'category_id' => 'required|string|max:1',
OKです！
ここは`size:1`でも良いですね！

2021-06-05 23:52 UTC, shimotaroo commented on src/resources/lang/ja/validation.php
> +    ],
👍

2021-06-05 23:52 UTC, merged