ユーザー登録画面作成
shimotaroo/Yanbaru-Qiita-App pull request #77
Opened 2021-06-04 14:50 UTC by Yuuichi-M

■ユーザー登録画面作成
・ルーティング(web.php)実装
・コントローラ(UsersController.php)作成・実装
・ビュー(register.blade.php)作成・実装

2021-06-05 01:14 UTC, shingo-suzumura commented on src/routes/web.php
> +Route::post('register', 'UsersController@register')->name('register.post');
コメントアウトで説明するのとてもわかりやすいです！
真似させていただきます！

2021-06-05 01:17 UTC, shingo-suzumura reviewed
LGTMです！

2021-06-06 12:55 UTC, shimotaroo requested changes
ユーザー登録、ログイン等の認証系のルーティングはLaravelが用意してくれている便利メソッドを使うことで簡単に実装できます。

18、20行目を削除して
```
Auth::routes();
```
を追記してみてください。

その後、コンテナ内で以下コマンドを実行してみてください。
```
$ php artisan route:list
```

認証系のルーティングが追加されているのがわかると思います。

なので今回作成いただいた`src/app/Http/Controllers/UsersController.php`は不要ですので削除してください。
（Laravel6系では認証系のコントローラーが既に準備されています）

また、`src/resources/views/welcome.blade.php`は使わないと思いますのでこのタイミングで削除しておいてください。ユーザー登録画面への遷移はヘッダーから行います。

以上です、修正対応よろしくお願いします😁

2021-06-06 12:55 UTC, shimotaroo commented on src/resources/views/register.blade.php
> +                        <input type="hidden" name="_token" value="">
CSRFトークンは
```
@csrf
```
を使うのが一般的です！
https://readouble.com/laravel/6.x/ja/csrf.html

2021-06-07 12:16 UTC, Yuuichi-M commented
ユーザー登録画面修正しました。
■修正点
・認証系ルーティング追記　Auth::routes();
・register.blade.php　CSRFトークンを@csrfに修正
・UsersController.php　welcome.blade.php削除
・register.blade.phpをsrc/resources/views/auth配下に移動

2021-06-07 13:07 UTC, shimotaroo approved these changes
LGTMです🎉🎉🎉
修正対応、バッチリです！
お疲れ様でした！

2021-06-08 12:32 UTC, shimotaroo approved these changes

2021-06-08 12:32 UTC, merged