ヘッダー作成（諸石）
shimotaroo/Yanbaru-Qiita-App pull request #84
Opened 2021-06-12 03:07 UTC by minami0601

ヘッダーを作成しました。
レビューお願いします。

## 【追加】
- ヘッダーの共通化
- `common`ディレクトリ作成→`header.blade.php`作成
- Font Awesome導入
- `css`に`header.css`追加
-  ページ毎にcssが読み込めるように`app.blade.php`の中に`@yield('css')`記載
- welcomeページのレイアウト共通化→共通化の流れを確認するため

## 【変更】
なし

## 【削除】
なし

## 【動作確認】
- やんばるQiita→トップページ（記事一覧画面作成中）
- ログイン→ログイン画面
- ユーザー登録→ユーザー登録画面
- 投稿する→他のPRで確認
- マイページ→他のPRで確認
- ログアウト→他のPRで確認

＠guest⇆＠authを変更して確認

ログイン前
<img width="1423" alt="スクリーンショット 2021-06-12 10 52 56" src="https://user-images.githubusercontent.com/65294836/121763078-3291e880-cb74-11eb-9362-f96f8a63a221.png">

ログイン後
<img width="1429" alt="スクリーンショット 2021-06-12 10 53 52" src="https://user-images.githubusercontent.com/65294836/121763088-42a9c800-cb74-11eb-85fb-1b05ae3f4143.png">

## 【特記事項】
なし

## 【仕様】
- 「投稿する」の左のアイコンはFont Awesomeを使用する→OK

2021-06-12 14:36 UTC, miki-mitsuki requested changes
確認しました。
全体的には細かいところまで考慮してくださっていて素晴らしいです。
何点か気になった点がありましたので、ご確認いただければと思います。

2021-06-12 14:36 UTC, miki-mitsuki commented on src/public/css/header.css
> +@import url('https://fonts.googleapis.com/css2?family=Righteous&display=swap');
事前の説明が不十分で申し訳ないのですが、コーディング規約のPSR-2にそって実装を進めていただきたいので、インデントはスペース4つでお願いします。

2021-06-12 14:36 UTC, miki-mitsuki commented on src/resources/views/welcome.blade.php
> +@section('css')
現在CSSをstyleタグで管理してくださっていますが、cssのコードの管理の視点から、styleタグを多様しない方が良いとされています。
（ styleタグを多用してしまうと、CSSがいろんなファイルに点在する形となり、修正対応が難しくなることがあるため）
そのため、
・クラスの使い方などを工夫して、CSSは1つのファイルで管理する
・@yield('css')では個別CSSファイルのリンク先だけ記載して、CSSは別ファイルにする
などで対応していただいた方が良いように感じました。

2021-06-12 22:23 UTC, minami0601 commented
修正しました。レビューお願いします。

## 修正箇所
- 不要な半角スペース削除
- インデントをスペース4つに変更
- `welcome.css`を作成してstyleタグを削除
  → 最終的にはwelcom.cssは使わないと思いますが、cssの読み込み方などを確認するために作成しました

2021-06-13 01:11 UTC, miki-mitsuki approved these changes
確認しました。
修正箇所全て問題ありません。

2021-06-13 01:11 UTC, merged