記事編集画面の実装
shimotaroo/Yanbaru-Qiita-App pull request #86
Opened 2021-06-13 06:30 UTC by shingo-suzumura

・`edit.blade.php`の作成。
・共通レイアウトのパスの変更。
・アクションを`store`メソッドから`update`メソッドに変更。
・各フォームのvalueを自分の投稿内容を取得するように変更。

2021-06-13 08:57 UTC, Yuuichi-M reviewed
１次レビュー完了しました。
LGTMです！問題ございません。

2021-06-13 23:47 UTC, shimotaroo requested changes
お疲れ様でした！
1点レビューコメント入れました！

- バリデーション
- バリデーションエラー時の入力値保持

などは編集処理のPRに入ってくるという認識なのでよろしくお願いします！

2021-06-13 23:47 UTC, shimotaroo commented on src/resources/views/articles/edit.blade.php
> -                        @method('PUT')
編集・更新はPUTで良かったですよ！（むしろPOSTは使わないかと）

2021-06-14 11:34 UTC, shingo-suzumura commented
レビューを反映しました。
確認お願いします！

2021-06-14 12:43 UTC, merged