ログイン画面作成
shimotaroo/Yanbaru-Qiita-App pull request #9
Opened 2021-03-17 12:46 UTC by ks24pon

・ログイン画面作成
login.blade.phpでログイン画面作成に変更。

画面定義書にはRemember MeとForgot Your Password?の記入はないんですが削除してもいいでしょうか？

2021-03-17 14:03 UTC, ryota100 commented
お疲れ様です。

ログイン、ログアウト問題なくできること、確認しました。
OK！です。

Remember MeとForgot Your Passwordについては、今回実装予定ではなく、進むとエラーになるものですので、混乱させるかもしれないので、ここだけ後ほど消しておいてもらえればと思います。

以上、宜しくお願いします。

2021-03-18 14:28 UTC, shimotaroo requested changes
レビューしました！

あと、りょうたさんのコメントの通りなので消してください！
基本的に画面定義書の通りにしてください！

>Remember MeとForgot Your Passwordについては、今回実装予定ではなく、進むとエラーになるものですので、混乱させるかもしれないので、ここだけ後ほど消しておいてもらえればと思います。

2021-03-18 14:28 UTC, shimotaroo commented on src/routes/web.php
> +Route::get('/home', 'HomeController@index')->name('home');
今回の開発でHomeControllerは使用しないのでこのルーティングは消しておきましょう！
ついでにHomeControllerも消しておきましょう〜！

2021-03-19 14:11 UTC, shimotaroo approved these changes
LGTMです〜！

2021-03-19 14:29 UTC, ryota100 commented
お疲れ様です。

ログアウトが出来なくなってしまったので、
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
を追加ください。

ただ、ログアウトする画面に遷移できるようになったら(必要なくなったら)
Route::get('/home', 'HomeController@index')->name('home');
は、折を見て削除してください。

追加して、ログアウトもできること確認できたら、pushください。もらえたらマージします。
宜しくお願いします。

2021-03-20 00:29 UTC, ks24pon commented
・ログインページなどが表示される記述を消してしまったので、Auth::routes();を追加。

レビューお願いします。

2021-03-20 01:10 UTC, ryota100 commented
OKです！

2021-03-20 01:13 UTC, ryota100 approved these changes

2021-03-20 01:14 UTC, merged