記事一覧画面のフロント部分を作成
shimotaroo/Yanbaru-Qiita-App pull request #91
Opened 2021-06-15 01:46 UTC by Kazuki1131

記事一覧画面のフロント部分を作成しました。
レビューをお願いします。

## 【追加】

- 記事のカード部分
- Gridシステムでカードの整列
- ページネーションのフロント
- FontAwesomeで指定されたアイコンの実装

## 【変更】
configのapp.phpのタイムゾーンを日本時間に変更

## 【削除】
なし

## 【動作確認】
<img width="400" alt="記事一覧画面(フロント)" src="https://user-images.githubusercontent.com/82161767/121979968-171e1c00-cdc6-11eb-9de8-41edf7f7a9cf.png">

## 【特記事項】
なし

## 【仕様】
アイコンはFontAwesomeを使用する→OK

2021-06-16 14:37 UTC, miki-mitsuki requested changes
確認しました。
各コメントの詳細に関しては、Zoomでお話させていただいた通りです。
修正お願いいたします。

2021-06-16 14:37 UTC, miki-mitsuki commented on src/resources/views/welcome.blade.php
> +                    <p><p class="d-inline ml-4">投稿日時</p><p class="d-inline ml-4">{{ NOW() }}</p></p>
pタグは段落を指定する役割を持つタグなので、重ねて使うことは基本的にはないです。
また、このような記述の仕方だと、タイトルの内容などが長くなったときに見出しの下に内容が潜り込んでしまうので、レイアウトの修正をしていただきたいです。

2021-06-16 14:37 UTC, miki-mitsuki commented on src/resources/views/welcome.blade.php
> +            <div class="card mx-auto w-75">
インデントつけていただきたいです。

2021-06-16 14:37 UTC, miki-mitsuki commented on src/resources/views/welcome.blade.php
> +            </div>
細かいですが、閉じタグの後ろに不要な半角スペースがありますのでご確認いただければと思います。

2021-06-17 15:07 UTC, Kazuki1131 commented
修正いたしました。レビューよろしくお願いいたします。

## 修正箇所
- pタグをdlタグに変更
- 文字数が多くなってもレイアウトが崩れないように修正
- インデントの修正
- 不要な半角スペースの削除

2021-06-18 01:53 UTC, closed without merging