記事投稿機能の実装
shimotaroo/Yanbaru-Qiita-App pull request #93
Opened 2021-06-16 11:52 UTC by shingo-suzumura

【変更点】
・`ArticleController`にstore処理の記述。
・ヘッダーから投稿画面へのリンクを追加。
・`web.php`に認証ユーザーのみのルーティングを追加。

2021-06-17 00:53 UTC, mitsumasaanan commented
Article.phpの「class Article extends Model{ 」に対する閉じカッコが抜けてますので、追加するようお願いします😁
他はLGTMです👏
認証ユーザーのみのルーティングの記述や、layouts.appからlayouts.viewへの細かい変更等もありがとうございます！

2021-06-17 15:21 UTC, shimotaroo requested changes
レビューしました！
少しだけ修正をお願いします！

2021-06-17 15:21 UTC, shimotaroo commented on src/app/Http/Controllers/ArticleController.php
>      public function store(ArticleRequest $request ,Article $article)
すみません、ここ修正箇所じゃないんですけど
,の前後のスペースの取り方がおかしいので修正して欲しいですm(__)m

2021-06-17 15:21 UTC, shimotaroo commented on src/resources/views/articles/create.blade.php
> +                            >
インデントがおかしいように見えます。
（他のinputタグと合わせましょう）

2021-06-17 15:21 UTC, shimotaroo commented on src/resources/views/articles/create.blade.php
> +@extends('layouts.view')
app.blade.phpを使わないのであればこの機会に削除しておきましょう！

2021-06-17 15:21 UTC, shimotaroo commented on src/resources/views/articles/create.blade.php
> +@extends('layouts.view')
app.blade.phpを使わないのであればこの機会に削除しておきましょう！

2021-06-17 15:21 UTC, shimotaroo commented on src/routes/web.php
>  Route::get('/home', 'HomeController@index')->name('home');
ここも修正箇所ではなく申し訳ないんですけど、
home.blade.phpは不要な画面だと思いますのでこの機会にルーティング、bladeファイルそれぞれ削除しておきましょう！

2021-06-18 08:40 UTC, shingo-suzumura commented
【2次レビュー後の変更点】
・`web.php`の`home.blade.php`のルーティングの削除
・`app.blade.php`の削除
・インデント、スペースの修正

2021-06-18 13:00 UTC, shimotaroo approved these changes
LGTMです！
（コーディング規約エラーは見逃します）

2021-06-18 13:00 UTC, shimotaroo commented on src/app/Article.php
> +        'title','category_id','summary','url'
前回見逃してましたが、`,`の後にはスペースが必要です！
今後気をつけましょう！

2021-06-18 13:00 UTC, shimotaroo commented on src/app/Article.php
>          return $this->belongsTo(User::class);
ここも範囲外ですが、モデルの書式は公式ドキュメントに合わせるのが無難かと思います！（修正主要）
https://readouble.com/laravel/6.x/ja/eloquent-relationships.html

2021-06-18 13:00 UTC, shimotaroo commented on src/app/Http/Controllers/ArticleController.php
> +    public function store(ArticleRequest $request,　Article $article)
ここも`,`の後にはスペースが必要です。

2021-06-18 13:00 UTC, shimotaroo commented on src/routes/web.php
> +    Route::resource('articles','ArticleController',['only'=>['create','store']]);
`,`後のスペース

2021-06-18 13:00 UTC, merged